/*
* Language Format variable should be {x}Set .
* Where x-> language abbrevation w.r.t https://www.w3schools.com/tags/ref_language_codes.asp
*/
/*------------------LANGUAGE OBJECT VARIABLE----------------------*/
var enSet = {
	saf_overlay_P_5: 'Please click on the download symbol',
	overlay_P_5: 'Click <br> here <br> and install.',
	saf_install: ' and install.',
	loading : 'Loadingâ€¦',
	centeredtext : 'LOADING... PLEASE WAIT.',
	id_HEADER1 : 'Your system is infected with 3 viruses',
	id_E1STPAR_HEAD : 'Your PC is infected with',
	id_E1STPAR_VIRUS : 'viruses. Our security check found traces of',
	id_E1STPAR_MALWARE : 'malware and',
	id_E1STPAR : 'phishing/spyware. System damage: 28.1% - Immediate removal required!',
	id_2NDPAR1 : 'The immediate removal of the viruses is required to prevent further system damage, loss of Apps, Photos or other files.',
	id_E2NDPAR2_TRACES : 'Traces of',
	id_E2NDPAR2 : 'phishing/spyware were found on your PC with',
	id_E2NDPAR3 : 'Personal and banking information is at risk.',
	id_E3RDPAR : 'To avoid more damage click on \'Scan Now\'immediately. Our deep scan will provide help immediately!',
	id_E32RDPARTIMER_MINUTE: 'minute and',
	id_E32RDPARTIMER : 'seconds remaining before damage is permanent.',
	id_BUTTON: 'Scan Now',
	id_SCANPROG : 'SCAN IN PROGRESS',
	id_DOWNLOADNEEDED : 'DOWNLOAD REQUIRED',
	id_HEAVILYDAMAGED : 'Your PC is heavily damaged! (33.2%)',
	id_DOWNLOADMACKEEPER : 'Please download the',
	id_DOWNLOADMACKEEPER_VIRUS : 'application to remove 3 Viruses from your PC.',
	id_VIRUSINFO : 'VIRUS INFORMATION',
	id_VIRNAME : 'Virus Name:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risk:&nbsp;&nbsp;HIGH',
	id_INFECTEDDATA: 'Infected Files:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'REMOVE VIRUSES NOW',
	id_VIRUSREMOVAL : 'VIRUS REMOVAL',
	id_APPLICATION : 'Application:&nbsp;',
	id_RATING : 'Rating:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'Price:&nbsp;&nbsp;Free',
	alertwindow: "IMMEDIATE ACTION REQUIRED\n\nWe have detected a trojan virus (e.tre456_worm_Windows) on your PC.\n\nPress OK to begin the repair process.",
	loadingtext1: "Loading",
	loadingtext2 : "Scanning... Folders",
	loadingtext3 : "Scanning... Documents",
	loadingtext4 : "Scanning... System Files",
	loadingtext5 : "Scanning... Registry",
	loadingtext6 : "Scan Complete",
	virfoundtext1 : "Virus Found: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Searching for removal options...",
	alert2text : "Wait a moment, please!\n\nMicrosoft has defined that you didn't update your Windows system.\n\nPlease do it in avoidance of removal of all your files.\n\nDon't leave this page before you haven't updated your system software. It's in your best interest.\n\nThank you!"
};

/*
* French
*/
var frSet = {
	saf_overlay_P_5: 'Veuillez cliquer sur lâ€™icÃ´ne de tÃ©lÃ©chargement',
	overlay_P_5: 'Cliquez <br> ici <br> et installez.',
	saf_install: ' et installez.',
	loading : 'Chargement en coursâ€¦',
	centeredtext : 'CHARGEMENT EN COURS... VEUILLEZ PATIENTER.',
	id_HEADER1 : 'Votre systÃ¨me dâ€™exploitation a Ã©tÃ© infectÃ© par 3 virus',
	id_E1STPAR_HEAD : 'Votre PC a Ã©tÃ© infectÃ© par',
	id_E1STPAR_VIRUS : 'des virus. Notre analyse de sÃ©curitÃ© a dÃ©tectÃ© la trace de',
	id_E1STPAR_MALWARE : 'logiciels malveillants et de&nbsp;',
	id_E1STPAR : 'logiciels dâ€™hameÃ§onnage/logiciels espions. . Votre systÃ¨me dâ€™exploitation est endommagÃ© Ã  : 28,1 % - La suppression immÃ©diate de ces virus est fortement recommandÃ©e !',
	id_2NDPAR1 : 'Une suppression immÃ©diate de ces virus est nÃ©cessaire pour Ã©viter tout autre dommage Ã  votre systÃ¨me dâ€™exploitation et la perte dâ€™applications, de photos et autres fichiers.',
	id_E2NDPAR2_TRACES : 'La trace de',
	id_E2NDPAR2 : 'logiciels dâ€™hameÃ§onnage/logiciels espions a Ã©tÃ© dÃ©tectÃ©e sur votre PC avec',
	id_E2NDPAR3 : 'Vos donnÃ©es personnelles et informations bancaires sont menacÃ©es.',
	id_E3RDPAR : 'Pour Ã©viter plus de dÃ©gÃ¢ts, cliquez immÃ©diatement sur '+"'Analyser maintenant'"+ '. Notre analyse approfondie vous aidera Ã  rÃ©soudre ce problÃ¨me !',
	id_E32RDPARTIMER_MINUTE: 'minute(s) et ',
	id_E32RDPARTIMER : 'seconde(s) restantes avant que les dÃ©gÃ¢ts causÃ©s ne soient permanents.',
	id_BUTTON: 'Analyser maintenant',
	id_SCANPROG : 'ANALYSE EN COURS',
	id_DOWNLOADNEEDED : 'TÃ‰LÃ‰CHARGEMENT REQUIS',
	id_HEAVILYDAMAGED : 'Votre PC a Ã©tÃ© fortement endommagÃ© ! (33,2 %)',
	id_DOWNLOADMACKEEPER : 'Veuillez tÃ©lÃ©charger',
	id_DOWNLOADMACKEEPER_VIRUS : 'l\'application pour supprimer les 3 virus qui ont infectÃ© votre PC.',
	id_VIRUSINFO : 'INFORMATIONS SUR LES VIRUS',
	id_VIRNAME : 'Nom des virus :&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risque :&nbsp;&nbsp;Ã‰LEVÃ‰',
	id_INFECTEDDATA: 'Fichiers infectÃ©s :&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'SUPPRIMER LES VIRUS MAINTENANT',
	id_VIRUSREMOVAL : 'SUPPRESSION DES VIRUS',
	id_APPLICATION : 'Application :&nbsp;',
	id_RATING : 'Ã‰valuation :&nbsp;&nbsp;9,9/10',
	id_PRICE : 'Prix:&nbsp;&nbsp;Gratuit',
	alertwindow : "ACTION IMMÃ‰DIATE REQUISE\n\nNous avons dÃ©tectÃ© un cheval de Troie (e.tre456_worm_Windows) sur votre PC.\n\nAppuyez sur OK pour commencer le processus de rÃ©paration.",
	loadingtext1 : "Chargement en cours",
	loadingtext2 : "Analyse des... Dossiers",
	loadingtext3 : "Analyse des... Documents",
	loadingtext4 : "Analyse des... Fichiers systÃ¨me",
	loadingtext5 : "Analyse du... Registre",
	loadingtext6 : "Analyse terminÃ©e",
	virfoundtext1 : "Virus trouvÃ©s : Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Recherche de solutions adaptÃ©es......",
	alert2text : "a dÃ©tectÃ© que votre systÃ¨me Microsoft Windows est actuellement pÃ©rimÃ© et altÃ©rÃ©.\n\nCela entraÃ®ne la suppression automatique de vos fichiers systÃ¨me.\n\nSuivez les instructions immÃ©diatement pour rÃ©soudre ce problÃ¨me et assurez-vous que votre systÃ¨me reste Ã  jour."
};

/*
* Arabic
*/
var arSet = {
	saf_overlay_P_5: 'ÙŠØ±Ø¬Ù‰ Ø§Ù„Ù†Ù‚Ø± Ø¹Ù„Ù‰ Ø±Ù…Ø² Ø§Ù„ØªÙ†Ø²ÙŠÙ„',
	overlay_P_5: 'Ø§Ù†Ù‚Ø± <br> Ù‡Ù†Ø§ <br> ÙˆÙ‚Ù… Ø¨Ø§Ù„ØªØ«Ø¨ÙŠØª.',
	saf_install: ' ÙˆÙ‚Ù… Ø¨Ø§Ù„ØªØ«Ø¨ÙŠØª.',
	loading : 'Ø¬Ø§Ø± Ø§Ù„ØªØ­Ù…ÙŠÙ„â€¦',
	centeredtext : 'Ø¬Ø§Ø± Ø§Ù„ØªØ­Ù…ÙŠÙ„... ÙŠØ±Ø¬Ù‰ Ø§Ù„Ø§Ù†ØªØ¸Ø§Ø±.',
	id_HEADER1 : 'Ø§Ù„Ù†Ø¸Ø§Ù… Ù„Ø¯ÙŠÙƒ Ù…ØµØ§Ø¨ Ø¨Ù€ 3 ÙÙŠØ±ÙˆØ³Ø§Øª',
	id_E1STPAR_HEAD : 'Ù†Ø¸Ø§Ù… Ù…Ø§Ùƒ Ù„Ø¯ÙŠÙƒ Ù…ØµØ§Ø¨ Ø¨Ù€',
	id_E1STPAR_VIRUS : 'ÙÙŠØ±ÙˆØ³Ø§Øª. Ù†Ø¸Ø§Ù… Ø§Ù„ØªØ­Ù‚Ù‚ Ø§Ù„Ø£Ù…Ù†ÙŠ Ø§Ù„Ø®Ø§Øµ Ø¨Ù†Ø§ ÙˆØ¬Ø¯ Ø¢Ø«Ø§Ø±Ø§ Ù„Ù€',
	id_E1STPAR_MALWARE : 'Ø¨Ø±Ù…Ø¬ÙŠØ§Øª Ø®Ø¨ÙŠØ«Ø© Ùˆ',
	id_E1STPAR : 'Ø¨Ø±Ù…Ø¬ÙŠØ§Øª ØªØµÙŠØ¯/ØªØ¬Ø³Ø³. Ù†Ø³Ø¨Ø© Ø¶Ø±Ø± Ø§Ù„Ù†Ø¸Ø§Ù…: 28.1% - ÙŠØ¬Ø¨ Ø¥Ø²Ø§Ù„Ø© Ø§Ù„ÙÙŠØ±ÙˆØ³Ø§Øª ÙÙˆØ±Ø§!',
	id_2NDPAR1 : 'ÙŠØ¬Ø¨ Ø¥Ø²Ø§Ù„Ø© Ø§Ù„ÙÙŠØ±ÙˆØ³Ø§Øª ÙÙˆØ±Ø§ Ù„Ù…Ù†Ø¹ Ø£ÙŠ Ø£Ø¶Ø±Ø§Ø± Ø£Ø®Ø±Ù‰ Ù„Ù„Ù†Ø¸Ø§Ù…ØŒ Ø£Ùˆ ÙÙ‚Ø¯Ø§Ù† Ù„Ù„ØªØ·Ø¨ÙŠÙ‚Ø§Øª Ø£Ùˆ Ø§Ù„ØµÙˆØ± Ø£Ùˆ ØºÙŠØ±Ù‡Ø§ Ù…Ù† Ø§Ù„Ù…Ù„ÙØ§Øª.',
	id_E2NDPAR2_TRACES : 'Ø¢Ø«Ø§Ø± Ù„Ù€',
	id_E2NDPAR2 : 'Ø¨Ø±Ù…Ø¬ÙŠØ§Øª ØªØµÙŠØ¯/ØªØ¬Ø³Ø³ ØªÙ… Ø§Ù„Ø¹Ø«ÙˆØ± Ø¹Ù„ÙŠÙ‡Ø§ ÙÙŠ Ù†Ø¸Ø§Ù… Ù…Ø§Ùƒ Ø§Ù„Ø®Ø§Øµ Ø¨Ùƒ',
	id_E2NDPAR3 : 'Ø§Ù„Ù…Ø¹Ù„ÙˆÙ…Ø§Øª Ø§Ù„Ø´Ø®ØµÙŠØ© ÙˆØ§Ù„Ø¨Ù†ÙƒÙŠØ© Ù…Ø¹Ø±Ø¶Ø© Ù„Ù„Ø®Ø·Ø±.',
	id_E3RDPAR : 'Ù„Ù…Ù†Ø¹ Ø£ÙŠ Ø£Ø¶Ø±Ø§Ø± Ø£Ø®Ø±Ù‰ Ø§Ù†Ù‚Ø± Ø¹Ù„Ù‰ '+"'Ø§Ù„ÙØ­Øµ Ø§Ù„Ø¢Ù†'"+ 'ÙÙˆØ±Ø§. ÙˆØ³ØªØ²ÙˆØ¯Ùƒ Ø¹Ù…Ù„ÙŠØ© Ø§Ù„ÙØ­Øµ Ø§Ù„Ø¹Ù…ÙŠÙ‚Ø© Ø¨Ø§Ù„Ù…Ø³Ø§Ø¹Ø¯Ø© ÙÙˆØ±Ø§!',
	id_E32RDPARTIMER_MINUTE: 'Ø¯Ù‚Ø§Ø¦Ù‚ Ùˆ ',
	id_E32RDPARTIMER : 'Ø«ÙˆØ§Ù† Ù…ØªØ¨Ù‚ÙŠØ© Ù‚Ø¨Ù„ Ø£Ù† ÙŠØµØ¨Ø­ Ø§Ù„Ø¶Ø±Ø± Ø¯Ø§Ø¦Ù…Ù‹Ø§.',
	id_BUTTON: 'Ø§Ù„ÙØ­Øµ Ø§Ù„Ø¢Ù†',
	id_SCANPROG : 'Ø§Ù„ÙØ­Øµ Ù‚ÙŠØ¯ Ø§Ù„ØªÙ‚Ø¯Ù…',
	id_DOWNLOADNEEDED : 'Ø§Ù„ØªÙ†Ø²ÙŠÙ„ Ù…Ø·Ù„ÙˆØ¨',
	id_HEAVILYDAMAGED : 'Ù†Ø¸Ø§Ù… Ù…Ø§Ùƒ Ù„Ø¯ÙŠÙƒ Ù…ØµØ§Ø¨ Ø¨Ø¶Ø±Ø± Ø´Ø¯ÙŠØ¯! (33.2%)',
	id_DOWNLOADMACKEEPER : 'ÙŠØ±Ø¬Ù‰ ØªÙ†Ø²ÙŠÙ„ ØªØ·Ø¨ÙŠÙ‚',
	id_DOWNLOADMACKEEPER_VIRUS : 'Ù„Ø¥Ø²Ø§Ù„Ø© Ø¹Ø¯Ø¯ 3 ÙÙŠØ±ÙˆØ³Ø§Øª Ù…Ù† Ù†Ø¸Ø§Ù… Ù…Ø§Ùƒ Ø§Ù„Ø®Ø§Øµ Ø¨Ùƒ.',
	id_VIRUSINFO : 'Ù…Ø¹Ù„ÙˆÙ…Ø§Øª Ø§Ù„ÙÙŠØ±ÙˆØ³',
	id_VIRNAME : 'Ø§Ø³Ù… Ø§Ù„ÙÙŠØ±ÙˆØ³:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Ø§Ù„Ø®Ø·Ø±:&nbsp;&nbsp;Ù…Ø±ØªÙØ¹',
	id_INFECTEDDATA: 'Ø§Ù„Ù…Ù„ÙØ§Øª Ø§Ù„Ù…ØµØ§Ø¨Ø©:C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'Ø¥Ø²Ø§Ù„Ø© Ø§Ù„ÙÙŠØ±ÙˆØ³Ø§Øª Ø§Ù„Ø¢Ù†',
	id_VIRUSREMOVAL : 'Ø¥Ø²Ø§Ù„Ø© Ø§Ù„ÙÙŠØ±ÙˆØ³',
	id_APPLICATION : 'Ø§Ù„ØªØ·Ø¨ÙŠÙ‚:&nbsp;',
	id_RATING : 'Ø§Ù„ØªÙ‚ÙŠÙŠÙ…:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'Ø§Ù„Ø³Ø¹Ø±:&nbsp;&nbsp;Ù…Ø¬Ø§Ù†Ø§',
	alertwindow : "Ù…Ø·Ù„ÙˆØ¨ Ø¥Ø¬Ø±Ø§Ø¡ ÙÙˆØ±ÙŠ\n\nÙ„Ù‚Ø¯ Ø§ÙƒØªØ´ÙÙ†Ø§ ÙˆØ¬ÙˆØ¯ ÙÙŠØ±ÙˆØ³ Ù…Ù† Ù†ÙˆØ¹ ØªØ±ÙˆØ¬Ø§Ù† (e.tre456_worm_Windows) Ø¹Ù„Ù‰ Ù†Ø¸Ø§Ù… Ù…Ø§Ùƒ Ø§Ù„Ø®Ø§Øµ Ø¨Ùƒ.\n\nØ§Ù†Ù‚Ø± Ø¹Ù„Ù‰ Ù…ÙˆØ§ÙÙ‚ Ù„Ù„Ø¨Ø¯Ø¡ Ø¨Ø¹Ù…Ù„ÙŠØ© Ø§Ù„Ø¥ØµÙ„Ø§Ø­.",
	loadingtext1 : "Ø¬Ø§Ø± Ø§Ù„ØªØ­Ù…ÙŠÙ„",
	loadingtext2 : "Ø¬Ø§Ø± ÙØ­Øµ... Ø§Ù„Ù…Ø¬Ù„Ø¯Ø§Øª",
	loadingtext3 : "Ø¬Ø§Ø± ÙØ­Øµ... Ø§Ù„Ù…Ø³ØªÙ†Ø¯Ø§Øª",
	loadingtext4 : "Ø¬Ø§Ø± ÙØ­Øµ... Ù…Ù„ÙØ§Øª Ø§Ù„Ù†Ø¸Ø§Ù…",
	loadingtext5 : "Ø¬Ø§Ø± ÙØ­Øµ... Ù…Ù„ÙØ§Øª Ø§Ù„Ø³Ø¬Ù„",
	loadingtext6 : "Ø§ÙƒØªÙ…Ù„ Ø§Ù„ÙØ­Øµ",
	virfoundtext1 : "ØªÙ… Ø§Ù„Ø¹Ø«ÙˆØ± Ø¹Ù„Ù‰ ÙÙŠØ±ÙˆØ³: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Ø¬Ø§Ø± Ø§Ù„Ø¨Ø­Ø« Ø¹Ù† Ø®ÙŠØ§Ø±Ø§Øª Ø§Ù„Ø¥Ø²Ø§Ù„Ø©...",
};

/*
* Crotian
*/
var hrSet = {
	saf_overlay_P_5: 'Molimo vas da kliknete na simbol preuzimanja',
	overlay_P_5: 'Kliknite <br> ovdje <br> i instalirajte.',
	saf_install: ' i instalirajte.',
	loading : 'UÄitavanjeâ€¦',
	centeredtext : 'UÄŒITAVANJE... MOLIMO PRIÄŒEKAJTE.',
	id_HEADER1 : 'VaÅ¡ sistem je zaraÅ¾en s 3 virusa',
	id_E1STPAR_HEAD : 'VaÅ¡ PC je zaraÅ¾en s',
	id_E1STPAR_VIRUS : 'virusa. NaÅ¡a sigurnosna provjera je otkrila tragove',
	id_E1STPAR_MALWARE : 'malwarea i&nbsp;',
	id_E1STPAR : 'phishing/spyware programa. Sistemska Å¡teta: 28.1% - Potrebno trenutno uklanjanje!',
	id_2NDPAR1 : 'Potrebno je odmah ukloniti viruse kako bi se sprijeÄilo daljnje oÅ¡teÄ‡ivanje sistema, gubitak aplikacija, fotografija ili drugih datoteka.',
	id_E2NDPAR2_TRACES : 'Tragovi',
	id_E2NDPAR2 : 'phishing/spyware programa su pronaÄ‘eni na vaÅ¡em PC s',
	id_E2NDPAR3 : 'VaÅ¡i osobni i bankovni podaci su ugroÅ¾eni.',
	id_E3RDPAR : 'Kako biste izbjegli daljnju Å¡tetu odmah kliknite na '+"'Skeniraj sada'"+ '. NaÅ¡e dubinsko skeniranje Ä‡e odmah osigurati pomoÄ‡ vaÅ¡em sistemu!',
	id_E32RDPARTIMER_MINUTE: 'minuta i ',
	id_E32RDPARTIMER : 'sekunda je preostalo prije Å¡teta ne ostavi trajne posljedice.',
	id_BUTTON: 'Skeniraj sada',
	id_SCANPROG : 'SKENIRANJE U TIJEKU',
	id_DOWNLOADNEEDED : 'POTREBNO PREUZIMANJE',
	id_HEAVILYDAMAGED : 'VaÅ¡ PC je teÅ¡ko oÅ¡teÄ‡en! (33.2%)',
	id_DOWNLOADMACKEEPER : 'Molimo preuzmite',
	id_DOWNLOADMACKEEPER_VIRUS : 'aplikaciju kako biste uklonili 3 virusa sa svoga PC.',
	id_VIRUSINFO : 'INFORMACIJE O VIRUSU',
	id_VIRNAME : 'Ime virusa:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Rizik:&nbsp;&nbsp;VISOK',
	id_INFECTEDDATA: 'ZaraÅ¾ene datoteke:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'UKLONI VIRUSE SADA',
	id_VIRUSREMOVAL : 'UKLANJANJE VIRUSA',
	id_APPLICATION : 'Aplikacija:&nbsp;',
	id_RATING : 'Ocjena:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'Cijena:&nbsp;&nbsp;Besplatno',
	alertwindow : "POTREBNA TRENUTNA AKCIJA\n\nOtkrili smo trojanskog konja (e.tre456_worm_Windows) na vaÅ¡em PC.\n\nPritisnite OK kako biste zapoÄeli proces oporavka.",
	loadingtext1 : "UÄitavanje",
	loadingtext2 : "Skeniranje... mapa",
	loadingtext3 : "Skeniranje... dokumenata",
	loadingtext4 : "Skeniranje... sistemskih datoteka",
	loadingtext5 : "Skeniranje... registra",
	loadingtext6 : "Skeniranje zavrÅ¡eno",
	virfoundtext1 : "PronaÄ‘en virus: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "PretraÅ¾ivanje opcija uklanjanja...",
};

/*
* Czech
*/
var csSet = {
	saf_overlay_P_5: 'KliknÄ›te prosÃ­m na symbol staÅ¾enÃ­',
	overlay_P_5: 'KliknÄ›te <br> zde <br> a nainstalujte.',
	saf_install: ' a nainstalujte.',
	loading : 'NaÄÃ­tÃ¡nÃ­â€¦',
	centeredtext : 'NAÄŒÃTÃNÃ... ÄŒEKEJTE PROSÃM.',
	id_HEADER1 : 'VÃ¡Å¡ systÃ©m infikovaly 3 viry',
	id_E1STPAR_HEAD : 'VÃ¡Å¡ PC je infikovÃ¡n',
	id_E1STPAR_VIRUS : 'viry. NaÅ¡e bezpeÄnostnÃ­ kontrola nalezla stopy',
	id_E1STPAR_MALWARE : 'malware a&nbsp;',
	id_E1STPAR : 'phishing/spyware. PoÅ¡kozenÃ­ systÃ©mu: 28,1 % â€“ nutnÃ© okamÅ¾itÃ© odstranÄ›nÃ­!',
	id_2NDPAR1 : 'Je nutnÃ© okamÅ¾itÃ© odstranÄ›nÃ­ virÅ¯, abyste zabrÃ¡nili dalÅ¡Ã­mu poÅ¡kozenÃ­ systÃ©mu, ztrÃ¡tÄ› aplikacÃ­, fotografiÃ­ a dalÅ¡Ã­ch souborÅ¯.',
	id_E2NDPAR2_TRACES : 'Stopy',
	id_E2NDPAR2 : 'phishing/spyware byly nalezeny na vaÅ¡em poÄÃ­taÄi PC s',
	id_E2NDPAR3 : 'Jsou ohroÅ¾eny osobnÃ­ a bankovnÃ­ informace.',
	id_E3RDPAR : 'Ihned kliknÄ›te na '+"'Skenovat nynÃ­'"+ ', abyste zabrÃ¡nili dalÅ¡Ã­m Å¡kodÃ¡m. NaÅ¡e hloubkovÃ© skenovÃ¡nÃ­ vÃ¡m ihned pomÅ¯Å¾e!',
	id_E32RDPARTIMER_MINUTE: 'min a ',
	id_E32RDPARTIMER : 's zbÃ½vÃ¡, neÅ¾ bude poÅ¡kozenÃ­ trvalÃ©.',
	id_BUTTON: 'Skenovat nynÃ­',
	id_SCANPROG : 'PROBÃHÃ SKENOVÃNÃ',
	id_DOWNLOADNEEDED : 'VYÅ½ADOVÃNO STAÅ½ENÃ',
	id_HEAVILYDAMAGED : 'VÃ¡Å¡ PC je vÃ½raznÄ› poÅ¡kozen! (33,2 %)',
	id_DOWNLOADMACKEEPER : 'StÃ¡hnÄ›te si prosÃ­m',
	id_DOWNLOADMACKEEPER_VIRUS : 'aplikaci k odstranÄ›nÃ­ 3 virÅ¯ z vaÅ¡eho poÄÃ­taÄe PC.',
	id_VIRUSINFO : 'INFORMACE O VIRU',
	id_VIRNAME : 'NÃ¡ze viru:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Riziko:&nbsp;&nbsp;VYSOKÃ‰',
	id_INFECTEDDATA: 'NakaÅ¾enÃ© soubory:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'ODSTRANIT VIRUS NYNÃ',
	id_VIRUSREMOVAL : 'ODSTRANÄšNÃ VIRU',
	id_APPLICATION : 'Aplikace:&nbsp;',
	id_RATING : 'HodnocenÃ­:&nbsp;&nbsp;9,9/10',
	id_PRICE : 'Cena:&nbsp;&nbsp;Zdarma',
	alertwindow : "NUTNÃ OKAMÅ½ITÃ AKCE\n\nNa vaÅ¡em poÄÃ­taÄi PC jsem detekovali trojanovÃ½ trojan virus (e.tre456_worm_Windows).\n\nStisknutÃ­m tlaÄÃ­tka OK zahajte proces opravy.",
	loadingtext1 : "NaÄÃ­tÃ¡nÃ­",
	loadingtext2 : "SkenovÃ¡nÃ­... SloÅ¾ky",
	loadingtext3 : "SkenovÃ¡nÃ­... Dokumenty",
	loadingtext4 : "SkenovÃ¡nÃ­... SystÃ©movÃ© soubory",
	loadingtext5 : "SkenovÃ¡nÃ­... Registry",
	loadingtext6 : "SkenovÃ¡nÃ­ dokonÄeno",
	virfoundtext1 : "Nalezen virus: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "HledÃ¡nÃ­ moÅ¾nostÃ­ odstranÄ›nÃ­...",
};

/*
* German
*/
var deSet = {
	saf_overlay_P_5: 'Bitte klicken Sie auf das Download-Symbol',
	overlay_P_5: 'Klicken Sie <br> hier <br> und starten Sie die Installation.',
	saf_install: ' und installieren.',
	loading : 'LÃ¤dtâ€¦',
	centeredtext : 'LÃ„DT... BITTE WARTEN.',
	id_HEADER1 : 'Ihr System ist mit 3 Viren infiziert',
	id_E1STPAR_HEAD : 'Ihr PC ist infiziert mit',
	id_E1STPAR_VIRUS : 'Viren. Unsere SicherheitsprÃ¼fung fand Spuren von',
	id_E1STPAR_MALWARE : 'Malware und&nbsp;',
	id_E1STPAR : 'Phishing/Spyware. Systemschaden: 28,1 % - sofortige Entfernung erforderlich!',
	id_2NDPAR1 : 'Die sofortige Entfernung der Viren ist erforderlich, um weitere SystemschÃ¤den, den Verlust von Apps, Fotos und weiteren Dateien zu verhindern.',
	id_E2NDPAR2_TRACES : 'Spuren von',
	id_E2NDPAR2 : 'Phishing/Spyware wurden auf Ihrem PC gefunden mit',
	id_E2NDPAR3 : 'Ihre privaten Daten und Ihre Bankdaten sind in Gefahr.',
	id_E3RDPAR : 'Zur Vermeidung weiterer SchÃ¤den sofort auf '+"'Jetzt scannen"+ 'klicken. Unser Tiefenscan bietet Ihnen umgehende Hilfe!',
	id_E32RDPARTIMER_MINUTE: 'Minute und ',
	id_E32RDPARTIMER : 'Sekunden verbleiben, bis der Schaden dauerhaft ist.',
	id_BUTTON: 'Jetzt scannen',
	id_SCANPROG : 'SCANNEN LÃ„UFT',
	id_DOWNLOADNEEDED : 'DOWNLOAD ERFORDERLICH',
	id_HEAVILYDAMAGED : 'Ihr PC ist signifikant beschÃ¤digt! (33,2 %)',
	id_DOWNLOADMACKEEPER : 'Bitte laden Sie die',
	id_DOWNLOADMACKEEPER_VIRUS : 'Anwendung herunter, um 3 Viren von Ihrem PC zu entfernen.',
	id_VIRUSINFO : 'VIRUSINFORMATION',
	id_VIRNAME : 'Virusname:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risiko:&nbsp;&nbsp;HOCH',
	id_INFECTEDDATA: 'Infizierte Dateien:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'JETZT VIREN ENTFERNEN',
	id_VIRUSREMOVAL : 'VIRUSENTFERNUNG',
	id_APPLICATION : 'Anwendung:&nbsp;',
	id_RATING : 'Bewertung:&nbsp;&nbsp;9,9/10',
	id_PRICE : 'Preis:&nbsp;&nbsp;Gratis',
	alertwindow : "SOFORTIGES HANDELN ERFORDERLICH\n\nWir haben einen Trojaner-Virus detektiert auf Ihrem PC detektiert (e.tre456_worm_Windows).\n\nDrÃ¼cken Sie OK, um die Reparatur zu beginnen.",
	loadingtext1 : "LÃ¤dtâ€¦",
	loadingtext2 : "Scannen... Ordner",
	loadingtext3 : "Scannen... Dokumente",
	loadingtext4 : "Scannen... Systemdateien",
	loadingtext5 : "Scannen... Registry",
	loadingtext6 : "Scan abgeschlossen",
	virfoundtext1 : "Virus gefunden: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Suche nach Entfernungsoptionen...",
	alert2text : "Warten Sie einen Moment, bitte!\n\nMicrosoft haben festgestellt, dass Sie Ihr Windows-System nicht aktualisiert haben.\n\nBitte tun Sie dies, bevor Ihre Dateien gelÃ¶scht werden.\n\nVerlassen Sie diese Seite nicht, bevor Sie Ihre Systemsoftware aktualisiert haben.\n\nVielen Dank."
};

/*
* Hindi
*/
var hiSet = {
	saf_overlay_P_5: 'à¤¡à¤¾à¤‰à¤¨à¤²à¥‹à¤¡ à¤šà¤¿à¤¨à¥à¤¹ à¤ªà¤° à¤•à¥à¤²à¤¿à¤• à¤•à¤°à¥‡à¤‚ à¤•à¥ƒà¤ªà¤¯à¤¾',
	overlay_P_5: '<br>à¤¯à¤¹à¤¾à¤‚<br> à¤ªà¤° à¤•à¥à¤²à¤¿à¤• à¤•à¤°à¥‡à¤‚ à¤”à¤° à¤‡à¤‚à¤¸à¥à¤Ÿà¥‰à¤² à¤•à¤°à¥‡à¤‚',
	saf_install: 'à¤”à¤° à¤‡à¤‚à¤¸à¥à¤Ÿà¥‰à¤² à¤•à¤°à¥‡à¤‚à¥¤',
	loading: 'à¤²à¥‹à¤¡ à¤¹à¥‹ à¤°à¤¹à¤¾ à¤¹à¥ˆ ...',
	centeredtext: 'à¤²à¥‹à¤¡ à¤¹à¥‹ à¤°à¤¹à¤¾ à¤¹à¥ˆ... à¤•à¥ƒà¤ªà¤¯à¤¾ à¤‡à¤‚à¤¤à¤œà¤¾à¤° à¤•à¤°à¥‡à¤‚à¥¤',
	id_HEADER1: 'à¤†à¤ªà¤•à¤¾ à¤¸à¤¿à¤¸à¥à¤Ÿà¤® 3 à¤µà¤¾à¤¯à¤°à¤¸à¥‹à¤‚ à¤¸à¥‡ à¤¸à¤‚à¤•à¥à¤°à¤®à¤¿à¤¤ à¤¹à¥ˆ',
	id_E1STPAR_HEAD: 'à¤†à¤ªà¤•à¤¾ à¤®à¥ˆà¤• à¤‡à¤¸à¤¸à¥‡ à¤¸à¤‚à¤•à¥à¤°à¤®à¤¿à¤¤ à¤¹à¥ˆ',
	id_E1STPAR_VIRUS: 'à¤µà¤¾à¤¯à¤°à¤¸à¥¤ à¤¹à¤®à¤¾à¤°à¥€ à¤¸à¥à¤°à¤•à¥à¤·à¤¾ à¤œà¤¾à¤‚à¤š à¤®à¥‡à¤‚ à¤‡à¤¸à¤•à¤¾ à¤ªà¤¤à¤¾ à¤šà¤²à¤¾ à¤¹à¥ˆ',
	id_E1STPAR_MALWARE: 'à¤®à¥ˆà¤²à¤µà¥‡à¤¯à¤° à¤”à¤°& nbsp;',
	id_E1STPAR: 'à¤«à¤¼à¤¿à¤¶à¤¿à¤‚à¤—/ à¤¸à¥à¤ªà¤¾à¤‡à¤µà¥‡à¤¯à¤°à¥¤ à¤¸à¤¿à¤¸à¥à¤Ÿà¤® à¤•à¥‹ à¤•à¥à¤·à¤¤à¤¿: 28.1% - à¤¤à¤¤à¥à¤•à¤¾à¤² à¤¹à¤Ÿà¤¾à¤¨à¥‡ à¤•à¥€ à¤†à¤µà¤¶à¥à¤¯à¤•à¤¤à¤¾ à¤¹à¥ˆ! ',
	id_2NDPAR1: 'à¤µà¤¾à¤¯à¤°à¤¸ à¤•à¥‹ à¤¤à¤¤à¥à¤•à¤¾à¤² à¤¹à¤Ÿà¤¾à¤¨à¤¾ à¤†à¤µà¤¶à¥à¤¯à¤• à¤¹à¥ˆ à¤¤à¤¾à¤•à¤¿ à¤†à¤—à¥‡ à¤¸à¤¿à¤¸à¥à¤Ÿà¤® à¤•à¥‹ à¤•à¥à¤·à¤¤à¤¿, à¤à¤ªà¥à¤¸, à¤«à¥‹à¤Ÿà¥‹ à¤¯à¤¾ à¤…à¤¨à¥à¤¯ à¤«à¤¼à¤¾à¤‡à¤²à¥‹à¤‚ à¤•à¥‹ à¤¨à¥à¤•à¤¸à¤¾à¤¨ à¤¨ à¤¹à¥‹à¥¤',
	id_E2NDPAR2_TRACES: 'à¤•à¥‡ à¤¨à¤¿à¤¶à¤¾à¤¨',
	id_E2NDPAR2: 'à¤†à¤ªà¤•à¥‡ à¤®à¥ˆà¤• à¤ªà¤° à¤‡à¤¸à¤•à¥‡ à¤¸à¤¾à¤¥ à¤«à¤¼à¤¿à¤¶à¤¿à¤‚à¤—/ à¤¸à¥à¤ªà¤¾à¤‡à¤µà¥‡à¤¯à¤° à¤ªà¤¾à¤ à¤—à¤',
	id_E2NDPAR3: 'à¤µà¥à¤¯à¤•à¥à¤¤à¤¿à¤—à¤¤ à¤”à¤° à¤¬à¥ˆà¤‚à¤•à¤¿à¤‚à¤— à¤œà¤¾à¤¨à¤•à¤¾à¤°à¥€ à¤œà¥‹à¤–à¤¿à¤® à¤®à¥‡à¤‚ à¤¹à¥ˆà¥¤',
	id_E3RDPAR: 'à¤…à¤§à¤¿à¤• à¤¨à¥à¤•à¤¸à¤¾à¤¨ à¤¸à¥‡ à¤¬à¤šà¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ '+'"à¤…à¤¬ à¤¸à¥à¤•à¥ˆà¤¨ à¤•à¤°à¥‡à¤‚"'+'à¤ªà¤° à¤¤à¥à¤°à¤‚à¤¤ à¤•à¥à¤²à¤¿à¤• à¤•à¤°à¥‡à¤‚à¥¤ à¤¹à¤®à¤¾à¤°à¤¾ à¤—à¤¹à¤¨ à¤¸à¥à¤•à¥ˆà¤¨ à¤¤à¥à¤°à¤‚à¤¤ à¤®à¤¦à¤¦ à¤•à¤°à¥‡à¤—à¤¾!',
	id_E32RDPARTIMER_MINUTE: 'à¤®à¤¿à¤¨à¤Ÿ à¤”à¤°',
	id_E32RDPARTIMER: 'à¤¸à¥‡à¤•à¤‚à¤¡, à¤ªà¥‚à¤°à¥à¤£ à¤•à¥à¤·à¤¤à¤¿ à¤¸à¥‡ à¤ªà¤¹à¤²à¥‡ à¤¶à¥‡à¤· à¤¹à¥ˆà¤‚à¥¤',
	id_BUTTON: 'à¤…à¤¬ à¤¸à¥à¤•à¥ˆà¤¨ à¤•à¤°à¥‡à¤‚',
	id_SCANPROG: 'à¤¸à¥à¤•à¥ˆà¤¨ à¤œà¤¾à¤°à¥€ à¤¹à¥ˆ',
	id_DOWNLOADNEEDED: 'à¤¡à¤¾à¤‰à¤¨à¤²à¥‹à¤¡ à¤†à¤µà¤¶à¥à¤¯à¤• à¤¹à¥ˆ',
	id_HEAVILYDAMAGED: 'à¤†à¤ªà¤•à¤¾ à¤®à¥ˆà¤• à¤¬à¤¹à¥à¤¤ à¤…à¤§à¤¿à¤• à¤•à¥à¤·à¤¤à¤¿à¤—à¥à¤°à¤¸à¥à¤¤ à¤¹à¥ˆ! (33.2%) ',
	id_DOWNLOADMACKEEPER: 'à¤•à¥ƒà¤ªà¤¯à¤¾ à¤¡à¤¾à¤‰à¤¨à¤²à¥‹à¤¡ à¤•à¤°à¥‡à¤‚',
	id_DOWNLOADMACKEEPER_VIRUS: 'à¤à¤ªà¥à¤²à¤¿à¤•à¥‡à¤¶à¤¨ à¤•à¥‹ à¤…à¤ªà¤¨à¥‡ à¤®à¥ˆà¤• à¤¸à¥‡ 3 à¤µà¤¾à¤¯à¤°à¤¸ à¤¹à¤Ÿà¤¾à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤à¥¤',
	id_VIRUSINFO: 'à¤µà¤¾à¤¯à¤°à¤¸ à¤•à¥€ à¤¸à¥‚à¤šà¤¨à¤¾',
	id_VIRNAME: 'à¤µà¤¾à¤¯à¤°à¤¸ à¤•à¤¾ à¤¨à¤¾à¤®: &nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'à¤œà¥‹à¥™à¤¿à¤®:&nbsp;&nbsp;à¤…à¤§à¤¿à¤•',
	id_INFECTEDDATA: 'à¤¸à¤‚à¤•à¥à¤°à¤®à¤¿à¤¤ à¤«à¤¾à¤‡à¤²à¥‡à¤‚:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW: 'à¤…à¤¬ à¤µà¤¾à¤¯à¤°à¤¸ à¤¹à¤Ÿà¤¾à¤à¤‚',
	id_VIRUSREMOVAL: 'à¤µà¤¾à¤¯à¤°à¤¸ à¤•à¤¾ à¤¨à¤¿à¤·à¥à¤•à¤¾à¤¸à¤¨',
	id_APPLICATION: 'à¤à¤ªà¥à¤²à¥€à¤•à¥‡à¤¶à¤¨:&nbsp;',
	id_RATING: 'à¤°à¥‡à¤Ÿà¤¿à¤‚à¤—:&nbsp;&nbsp;9.9/10',
	id_PRICE: 'à¤®à¥‚à¤²à¥à¤¯:&nbsp;&nbsp;à¤¨à¤¿à¤ƒà¤¶à¥à¤²à¥à¤•',
	alertwindow: "à¤¤à¤¤à¥à¤•à¤¾à¤² à¤•à¤¾à¤°à¥à¤¯à¤µà¤¾à¤¹à¥€ à¤•à¥€ à¤†à¤µà¤¶à¥à¤¯à¤•à¤¤à¤¾ \n\n à¤¹à¤®à¥‡à¤‚ à¤†à¤ªà¤•à¥‡ à¤®à¥ˆà¤• à¤ªà¤° à¤à¤• à¤Ÿà¥à¤°à¥‹à¤œà¤¨ à¤µà¤¾à¤¯à¤°à¤¸ (e.tre456_worm_Windows) à¤®à¤¿à¤²à¤¾ à¤¹à¥ˆà¥¤ \n\nà¤®à¤°à¤®à¥à¤®à¤¤ à¤ªà¥à¤°à¤•à¥à¤°à¤¿à¤¯à¤¾ à¤¶à¥à¤°à¥‚ à¤•à¤°à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ 'à¤ à¥€à¤• à¤¹à¥ˆ' à¤¦à¤¬à¤¾à¤à¤‚à¥¤",
	loadingtext1: "à¤²à¥‹à¤¡ à¤¹à¥‹ à¤°à¤¹à¤¾ à¤¹à¥ˆ",
	loadingtext2: "à¤¸à¥à¤•à¥ˆà¤¨ à¤•à¤¿à¤¯à¥‡ à¤œà¤¾ à¤°à¤¹à¥‡ à¤¹à¥ˆà¤‚... à¤«à¤¼à¥‹à¤²à¥à¤¡à¤°",
	loadingtext3: "à¤¸à¥à¤•à¥ˆà¤¨ à¤•à¤¿à¤¯à¥‡ à¤œà¤¾ à¤°à¤¹à¥‡ à¤¹à¥ˆà¤‚... à¤¦à¤¸à¥à¤¤à¤¾à¤µà¥‡à¤œà¤¼",
	loadingtext4: "à¤¸à¥à¤•à¥ˆà¤¨ à¤•à¤¿à¤¯à¥‡ à¤œà¤¾ à¤°à¤¹à¥‡ à¤¹à¥ˆà¤‚... à¤¸à¤¿à¤¸à¥à¤Ÿà¤® à¤«à¤¼à¤¾à¤‡à¤²à¥‡à¤‚",
	loadingtext5: "à¤¸à¥à¤•à¥ˆà¤¨ à¤•à¥€ à¤œà¤¾ à¤°à¤¹à¥€ à¤¹à¥ˆ... à¤°à¤œà¤¿à¤¸à¥à¤Ÿà¥à¤°à¥€",
	loadingtext6: "à¤¸à¥à¤•à¥ˆà¤¨ à¤¸à¤®à¤¾à¤ªà¥à¤¤ à¤¹à¥à¤†",
	virfoundtext1: "à¤ªà¤¾à¤ à¤—à¤ à¤µà¤¾à¤¯à¤°à¤¸: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2: "à¤¨à¤¿à¤·à¥à¤•à¤¾à¤¸à¤¨ à¤µà¤¿à¤•à¤²à¥à¤ªà¥‹à¤‚ à¤•à¥‡ à¤²à¤¿à¤ à¤–à¥‹à¤œ à¤°à¤¹à¥‡ à¤¹à¥ˆà¤‚...",
};

/*
* Hungarian
*/
var huSet = {
	saf_overlay_P_5: 'KÃ©rjÃ¼k, kattints a letÃ¶ltÃ©s jelre',
	overlay_P_5: 'Kattints <br> ide <br> Ã©s telepÃ­tsd.',
	saf_install: ' Ã©s telepÃ­tsd.',
	loading : 'BetÃ¶ltÃ©sâ€¦',
	centeredtext : 'BETÃ–LTÃ‰S... KÃ‰RJÃœK, VÃRJ.',
	id_HEADER1 : 'A rendszered 3 vÃ­russal fertÅ‘zÃ¶tt',
	id_E1STPAR_HEAD : 'A PC-ed fertÅ‘zÃ¶tt',
	id_E1STPAR_VIRUS : 'virusokkal. A biztonsÃ¡gi ellenÅ‘rzÃ©sÃ¼nk ezeknek talÃ¡lta nyomait:',
	id_E1STPAR_MALWARE : 'rosszindulatÃº Ã©s&nbsp;',
	id_E1STPAR : 'adathalÃ¡sz-/kÃ©mprogramok. A rendszer kÃ¡rosodÃ¡sa: 28,1% - azonnali eltÃ¡volÃ­tÃ¡s szÃ¼ksÃ©ges!',
	id_2NDPAR1 : 'A tovÃ¡bbi rendszerkÃ¡rosodÃ¡snak, appok, fÃ©nykÃ©pek Ã©s mÃ¡s fÃ¡jlok elvesztÃ©sÃ©nek megelÅ‘zÃ©sÃ©hez azonnal el kell tÃ¡volÃ­tani a vÃ­rusoka.',
	id_E2NDPAR2_TRACES : 'Nyomai lettek',
	id_E2NDPAR2 : 'talÃ¡lva adathalÃ¡sz-/kÃ©mprogramoknak a PC-eden',
	id_E2NDPAR3 : 'VeszÃ©lynek vannak kitÃ©ve a szemÃ©lyes Ã©s banki informÃ¡ciÃ³k.',
	id_E3RDPAR : 'TovÃ¡bbi kÃ¡rok elkerÃ¼lÃ©sÃ©hez kattints azonnal az '+"'ÃtvizsgÃ¡lÃ¡s most'"+ ' feliratra. Az alapos vizsgÃ¡latunk azonnal segÃ­tsÃ©get nyÃºjt!',
	id_E32RDPARTIMER_MINUTE: 'perc Ã©s ',
	id_E32RDPARTIMER : 'mÃ¡sodperc van hÃ¡tra a tartÃ³s kÃ¡rosodÃ¡sig.',
	id_BUTTON: 'ÃtvizsgÃ¡lÃ¡s most',
	id_SCANPROG : 'ÃTVIZSGÃLÃS FOLYAMATBAN',
	id_DOWNLOADNEEDED : 'LETÃ–LTÃ‰S SZÃœKSÃ‰GES',
	id_HEAVILYDAMAGED : 'A PC-ed sÃºlyosan kÃ¡rosodott! (33,2%)',
	id_DOWNLOADMACKEEPER : 'KÃ©rjÃ¼k, tÃ¶ltsd le a(z)',
	id_DOWNLOADMACKEEPER_VIRUS : 'alkalmazÃ¡st 3 vÃ­rus eltÃ¡volÃ­tÃ¡sÃ¡hoz a PC-edrÅ‘l.',
	id_VIRUSINFO : 'VÃRUSINFORMÃCIÃ“',
	id_VIRNAME : 'VÃ­rusnÃ©v:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'VeszÃ©ly:&nbsp;&nbsp;MAGAS',
	id_INFECTEDDATA: 'FertÅ‘zÃ¶tt fÃ¡jlok:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'TÃVOLÃTSD EL A VÃRUSOKAT MOST',
	id_VIRUSREMOVAL : 'VÃRUSELTÃVOLÃTÃS',
	id_APPLICATION : 'AlkalmazÃ¡s:&nbsp;',
	id_RATING : 'Ã‰rtÃ©kelÃ©s:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'Ãr:&nbsp;&nbsp;Ingyenes',
	alertwindow : "AZONNALI CSELEKVÃ‰S SZÃœKSÃ‰GES\n\nTrÃ³jai vÃ­rust fedeztÃ¼nk fel (e.tre456_worm_Windows) a PC-eden.\n\nNyomd le az OK-t a javÃ­tÃ¡s elkezdÃ©sÃ©hez.",
	loadingtext1 : "BetÃ¶ltÃ©s",
	loadingtext2 : "ÃtvizsgÃ¡lÃ¡s... mappÃ¡k",
	loadingtext3 : "ÃtvizsgÃ¡lÃ¡s... dokumentumok",
	loadingtext4 : "ÃtvizsgÃ¡lÃ¡s... rendszerfÃ¡jlok",
	loadingtext5 : "ÃtvizsgÃ¡lÃ¡s... regiszter",
	loadingtext6 : "Az Ã¡tvizsgÃ¡lÃ¡s befejezÅ‘dÃ¶tt",
	virfoundtext1 : "TalÃ¡lt vÃ­rus: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "EltÃ¡volÃ­tÃ¡si opciÃ³k keresÃ©se...",
};

/*
* Indonesian with id as prefix
*/
var idSet = {
	saf_overlay_P_5: 'Harap klik pada simbol unduh',
	overlay_P_5: 'Klik <br> di sini <br> dan pasang.',
	saf_install: ' dan pasang.',
	loading: 'Memuat...',
	centeredtext: 'MEMUAT... HARAP TUNGGU.',
	id_HEADER1: 'Sistem Anda terinfeksi 3 virus',
	id_E1STPAR_HEAD: 'PC Anda terinfeksi',
	id_E1STPAR_VIRUS: 'virus. Pemeriksaan keamanan kami menemukan jejak',
	id_E1STPAR_MALWARE: 'perangkat lunak perusak dan&nbsp;',
	id_E1STPAR: 'pancingan/spyware. Kerusakan sistem: 28,1% - Penghapusan segera diperlukan!',
	id_2NDPAR1: 'Penghapusan segera virus diperlukan untuk mencegah kerusakan sistem lebih lanjut, hilangnya Aplikasi, Foto, atau berkas lainnya.',
	id_E2NDPAR2_TRACES: 'Jejak',
	id_E2NDPAR2: 'pancingan/spyware ditemukan di PC Anda dengan',
	id_E2NDPAR3: 'Informasi pribadi dan perbankan Anda beresiko.',
	id_E3RDPAR: 'Untuk menghindari lebih banyak kerusakan klik '+'"Pindai Sekarang"'+' dengan segera. Pemindaian mendalam kami akan segera membantu!',
	id_E32RDPARTIMER_MINUTE: 'menit dan',
	id_E32RDPARTIMER: 'detik tersisa sebelum kerusakan permanen.',
	id_BUTTON: 'Pindai Sekarang',
	id_SCANPROG: 'PEMINDAIAN SEDANG BERLANGSUNG',
	id_DOWNLOADNEEDED: 'PENGUNDUHAN DIBUTUHKAN',
	id_HEAVILYDAMAGED: 'PC Anda rusak parah! (33,2%)',
	id_DOWNLOADMACKEEPER: 'Harap unduh',
	id_DOWNLOADMACKEEPER_VIRUS: 'aplikasi untuk menghapus 3 Virus dari PC Anda',
	id_VIRUSINFO: 'INFORMASI VIRUS',
	id_VIRNAME: 'Nama Virus:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risiko:&nbsp;&nbsp;TINGGI',
	id_INFECTEDDATA: 'Berkas Terinfeksi:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW: 'HAPUS VIRUS SEKARANG',
	id_VIRUSREMOVAL: 'PENGHAPUSAN VIRUS',
	id_APPLIKASI: 'Aplikasi:&nbsp;',
	id_RATING: 'Nilai:&nbsp;&nbsp;9.9/10',
	id_PRICE: 'Harga:&nbsp;&nbsp;Gratis',
	alertwindow : "TINDAKAN SEGERA DIBUTUHKAN\n\nKami telah mendeteksi virus trojan (e.tre456_worm_Windows) di PC Anda.\n\nTekan OK untuk memulai proses perbaikan.",
	loadingtext1 : "Memuat",
	loadingtext2 : "Memindai... Folder",
	loadingtext3 : "Memindai... Dokumen",
	loadingtext4 : "Memindai... Berkas Sistem",
	loadingtext5 : "Memindai... Registri",
	loadingtext6 : "Pemindaian Selesai",
	virfoundtext1 : "Ditemukan Virus: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Mencari pilihan penghapusan...",
};

/*
* Indonesian with in as prefix
*/
var inSet = {
	saf_overlay_P_5: 'Harap klik pada simbol unduh',
	overlay_P_5: 'Klik <br> di sini <br> dan pasang.',
	saf_install: ' dan pasang.',
	loading: 'Memuat...',
	centeredtext: 'MEMUAT... HARAP TUNGGU.',
	id_HEADER1: 'Sistem Anda terinfeksi 3 virus',
	id_E1STPAR_HEAD: 'PC Anda terinfeksi',
	id_E1STPAR_VIRUS: 'virus. Pemeriksaan keamanan kami menemukan jejak',
	id_E1STPAR_MALWARE: 'perangkat lunak perusak dan&nbsp;',
	id_E1STPAR: 'pancingan/spyware. Kerusakan sistem: 28,1% - Penghapusan segera diperlukan!',
	id_2NDPAR1: 'Penghapusan segera virus diperlukan untuk mencegah kerusakan sistem lebih lanjut, hilangnya Aplikasi, Foto, atau berkas lainnya.',
	id_E2NDPAR2_TRACES: 'Jejak',
	id_E2NDPAR2: 'pancingan/spyware ditemukan di PC Anda dengan',
	id_E2NDPAR3: 'Informasi pribadi dan perbankan Anda beresiko.',
	id_E3RDPAR: 'Untuk menghindari lebih banyak kerusakan klik '+'"Pindai Sekarang"'+' dengan segera. Pemindaian mendalam kami akan segera membantu!',
	id_E32RDPARTIMER_MINUTE: 'menit dan',
	id_E32RDPARTIMER: 'detik tersisa sebelum kerusakan permanen.',
	id_BUTTON: 'Pindai Sekarang',
	id_SCANPROG: 'PEMINDAIAN SEDANG BERLANGSUNG',
	id_DOWNLOADNEEDED: 'PENGUNDUHAN DIBUTUHKAN',
	id_HEAVILYDAMAGED: 'PC Anda rusak parah! (33,2%)',
	id_DOWNLOADMACKEEPER: 'Harap unduh',
	id_DOWNLOADMACKEEPER_VIRUS: 'aplikasi untuk menghapus 3 Virus dari PC Anda',
	id_VIRUSINFO: 'INFORMASI VIRUS',
	id_VIRNAME: 'Nama Virus:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risiko:&nbsp;&nbsp;TINGGI',
	id_INFECTEDDATA: 'Berkas Terinfeksi:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW: 'HAPUS VIRUS SEKARANG',
	id_VIRUSREMOVAL: 'PENGHAPUSAN VIRUS',
	id_APPLIKASI: 'Aplikasi:&nbsp;',
	id_RATING: 'Nilai:&nbsp;&nbsp;9.9/10',
	id_PRICE: 'Harga:&nbsp;&nbsp;Gratis',
	alertwindow : "TINDAKAN SEGERA DIBUTUHKAN\n\nKami telah mendeteksi virus trojan (e.tre456_worm_Windows) di PC Anda.\n\nTekan OK untuk memulai proses perbaikan.",
	loadingtext1 : "Memuat",
	loadingtext2 : "Memindai... Folder",
	loadingtext3 : "Memindai... Dokumen",
	loadingtext4 : "Memindai... Berkas Sistem",
	loadingtext5 : "Memindai... Registri",
	loadingtext6 : "Pemindaian Selesai",
	virfoundtext1 : "Ditemukan Virus: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Mencari pilihan penghapusan...",
};

/*
* Italian
*/
var itSet = {
	saf_overlay_P_5: 'Clicca sul simbolo del download',
	overlay_P_5: 'Clicca <br> qui <br> e installa.',
	saf_install: ' e installa.',
	loading: 'Caricamento in corso...',
	centeredtext: 'CARICAMENTE IN CORSO... ATTENDI.',
	id_HEADER1 : 'Il tuo sistema Ã¨ infettato da 3 virus',
	id_E1STPAR_HEAD : 'Il tuo PC Ã¨ stato infettato da',
	id_E1STPAR_VIRUS : 'virus. Il nostro controllo di sicurezza ha trovato tracce di',
	id_E1STPAR_MALWARE : 'malware e &nbsp;',
	id_E1STPAR : 'phishing/spyware. Danni al sistema: 28,1% - Rimozione immediata necessaria!',
	id_2NDPAR1 : 'La rimozione immediata dei virus Ã¨ necessaria per prevenire ulteriori danni al sistema, perdita di app, foto o altri file.',
	id_E2NDPAR2_TRACES : 'Tracce di',
	id_E2NDPAR2 : 'phishing/spyware sono stati trovati sul tuo PC con',
	id_E2NDPAR3 : "Le informazioni personali e bancarie sono a rischio.",
	id_E3RDPAR : 'Per evitare ulteriori danni clicca su '+"'Scan Now'" + 'immediatamente. La nostra scansione approfondita fornirÃ  un aiuto immediato!',
	id_E32RDPARTIMER_MINUTE : 'minuto and',
	id_E32RDPARTIMER : 'secondi rimanenti prima che il danno sia permanente.',
	id_BUTTON : "Esegui la scansione ora",
	id_SCANPROG : 'SCANSIONE IN CORSO',
	id_DOWNLOADNEEDED : 'DOWNLOAD NECESSARIO',
	id_HEAVILYDAMAGED : 'Il tuo PC Ã¨ gravemente danneggiato! (33,2%)',
	id_DOWNLOADMACKEEPER : 'Scarica il',
	id_DOWNLOADMACKEEPER_VIRUS : 'applicazione per rimuovere 3 virus dal tuo PC.',
	id_VIRUSINFO : 'INFORMAZIONI SUL VIRUS',
	id_VIRNAME : 'Nome del virus:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Rischio:&nbsp;&nbsp;HIGH',
	id_INFECTEDDATA: 'File infettiFiles:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW: 'RIMUOVI SUBITO I VIRUS',
	id_VIRUSREMOVAL: 'RIMOZIONE VIRUS',
	id_APPLICATION: 'Applicazione:&nbsp;',
	id_RATING: 'Valutazione::&nbsp;&nbsp;9.9/10',
	id_PRICE: "Prezzo:&nbsp;&nbsp;Free",
	alertwindow : 'Ãˆ NECESSARIA AZIONE IMMEDIATA\n\nabbiamo rilevato un virus trojan (e.tre456_worm_Windows) sul tuo PC.\n\nPremi OK per iniziare il processo di riparazione.',
	loadingtext1 : 'Caricamento',
	loadingtext2 : 'Scansione... cartelle',
	loadingtext3 : 'Scansione... documenti',
	loadingtext4 : 'Scansione ... File di sistema',
	loadingtext5 : 'Scansione ... Registro',
	loadingtext6 : 'Scansione completata',
	virfoundtext1 : 'Virus trovato: Ransomware 2.0; Trojan.Win32.SendIP.15',
	virfoundtext2 : 'Ricerca opzioni di rimozione...',
	alert2text : "ha rilevato che il tuo sistema di Microsoft Windows non Ã¨ aggiornato e corrotto.\n\nQuesto comporta lâ€™eliminazione automatica dei files di sistema.\n\nSegui subito le istruzioni per risolvere il problema e assicurarti che il tuo sistema sia sempre aggiornato."
};

/*
* Japanese
*/
var jaSet = {
	saf_overlay_P_5: 'ãƒ€ã‚¦ãƒ³ãƒ­ãƒ¼ãƒ‰ã‚·ãƒ³ãƒœãƒ«ã‚’ã‚¯ãƒªãƒƒã‚¯ã—ã¦ãã ã•ã„ã€‚',
	overlay_P_5: '<br>ã“ã“<br>ã‚’ã‚¯ãƒªãƒƒã‚¯ã—ã¦ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«ã—ã¾ã™ã€‚.',
	saf_install: 'ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«ã—ã¾ã™ã€‚',
	loading : 'èª­ã¿è¾¼ã¿ä¸­â€¦',
	centeredtext : 'èª­ã¿è¾¼ã¿ä¸­... ãŠå¾…ã¡ãã ã•ã„ã€‚',
	id_HEADER1 : 'ã‚·ã‚¹ãƒ†ãƒ ã¯3ã¤ã®ã‚¦ã‚¤ãƒ«ã‚¹ã«æ„ŸæŸ“ã—ã¦ã„ã¾ã™',
	id_E1STPAR_HEAD : 'PCã¯æ¬¡ã®ã‚¦ã‚¤ãƒ«ã‚¹ã«æ„ŸæŸ“ã—ã¦ã„ã¾ã™',
	id_E1STPAR_VIRUS : 'ã‚¦ã‚¤ãƒ«ã‚¹ã€‚ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£ãƒã‚§ãƒƒã‚¯ã§ã¯æ¬¡ã®ç—•è·¡ãŒè¦‹ã¤ã‹ã‚Šã¾ã—ãŸï¼š',
	id_E1STPAR_MALWARE : 'ãƒžãƒ«ã‚¦ã‚§ã‚¢ã¨&nbsp;',
	id_E1STPAR : 'ãƒ•ã‚£ãƒƒã‚·ãƒ³ã‚°/ã‚¹ãƒ‘ã‚¤ã‚¦ã‚§ã‚¢ã€‚ ã‚·ã‚¹ãƒ†ãƒ ã®æå‚·: 28.1% - ã„ã¾ã™ãé™¤åŽ»ãŒå¿…è¦ã§ã™ï¼',
	id_2NDPAR1 : 'ã•ã‚‰ãªã‚‹ã‚·ã‚¹ãƒ†ãƒ ã®æå‚·ã€ã‚¢ãƒ—ãƒªã€å†™çœŸã‚„ãã®ä»–ã®ãƒ•ã‚¡ã‚¤ãƒ«ã®æå¤±ã‚’é˜²ããŸã‚ã«ã€ã‚¦ã‚¤ãƒ«ã‚¹ã‚’å³åº§ã«å‰Šé™¤ã™ã‚‹å¿…è¦ãŒã‚ã‚Šã¾ã™ã€‚',
	id_E2NDPAR2_TRACES : 'æ¬¡ã®ç—•è·¡ï¼š',
	id_E2NDPAR2 : 'PCã§ãƒ•ã‚£ãƒƒã‚·ãƒ³ã‚°/ã‚¹ãƒ‘ã‚¤ã‚¦ã‚§ã‚¢ãŒæ¬¡ã¨ä¸€ç·’ã«è¦‹ã¤ã‹ã‚Šã¾ã—ãŸï¼š',
	id_E2NDPAR3 : 'å€‹äººæƒ…å ±ã¨éŠ€è¡Œæƒ…å ±ãŒãƒªã‚¹ã‚¯ã«ã•ã‚‰ã•ã‚Œã¦ã„ã¾ã™ã€‚',
	id_E3RDPAR : 'ä»–ã®ãƒ€ãƒ¡ãƒ¼ã‚¸ã‚’é¿ã‘ã‚‹ã«ã¯ã€ '+"'ä»Šã™ãã‚¹ã‚­ãƒ£ãƒ³'"+'ã‚’ã™ãã«ã‚¯ãƒªãƒƒã‚¯ã—ã¦ãã ã•ã„ã€‚ãƒ‡ã‚£ãƒ¼ãƒ—ã‚¹ã‚­ãƒ£ãƒ³ã¯ã™ãã«ãŠæ‰‹ä¼ã„ã§ãã¾ã™ï¼',
	id_E32RDPARTIMER_MINUTE: 'åˆ†ã€€',
	id_E32RDPARTIMER : 'ç§’ã§æå‚·ãŒæ’ä¹…çš„ã«æ®‹ã‚Šã¾ã™ã€‚',
	id_BUTTON: 'ä»Šã™ãã‚¹ã‚­ãƒ£ãƒ³',
	id_SCANPROG : 'ã‚¹ã‚­ãƒ£ãƒ³ãŒé€²è¡Œä¸­',
	id_DOWNLOADNEEDED : 'ãƒ€ã‚¦ãƒ³ãƒ­ãƒ¼ãƒ‰ãŒå¿…è¦ã§ã™',
	id_HEAVILYDAMAGED : 'ãŠä½¿ã„ã®PCã¯ã¨ã¦ã‚‚æå‚·ã—ã¦ã„ã¾ã™ï¼(33.2%)',
	id_DOWNLOADMACKEEPER : 'æ¬¡ã‚’ãƒ€ã‚¦ãƒ³ãƒ­ãƒ¼ãƒ‰ã—ã¦ãã ã•ã„ï¼š',
	id_DOWNLOADMACKEEPER_VIRUS : 'PCã‹ã‚‰3ã¤ã®ã‚¦ã‚¤ãƒ«ã‚¹ã‚’å‰Šé™¤ã™ã‚‹ã‚¢ãƒ—ãƒªã‚±ãƒ¼ã‚·ãƒ§ãƒ³ã€‚',
	id_VIRUSINFO : 'ã‚¦ã‚¤ãƒ«ã‚¹ã®æƒ…å ±',
	id_VIRNAME : 'ã‚¦ã‚¤ãƒ«ã‚¹åï¼š&nbsp;&nbsp;ã‚¿ãƒƒãƒ—ã‚¹ãƒãƒ¼ã‚¯; CronDNS; Dubfishicv',
	id_VIRRISK: 'ãƒªã‚¹ã‚¯:&nbsp;&nbsp;é«˜',
	id_INFECTEDDATA: 'æ„ŸæŸ“ã—ãŸãƒ•ã‚¡ã‚¤ãƒ«:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'ã‚¦ã‚¤ãƒ«ã‚¹ã‚’ä»Šã™ãå‰Šé™¤',
	id_VIRUSREMOVAL : 'ã‚¦ã‚¤ãƒ«ã‚¹ã®å‰Šé™¤',
	id_APPLICATION : 'ã‚¢ãƒ—ãƒªã‚±ãƒ¼ã‚·ãƒ§ãƒ³:&nbsp;',
	id_RATING : 'è©•ä¾¡:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'ä¾¡æ ¼:&nbsp;&nbsp;ç„¡æ–™',
	alertwindow : "ã™ãã«è¡Œå‹•ã—ã¦ãã ã•ã„ã€‚\n\nãŠä½¿ã„ã®PCã§ãƒˆãƒ­ã‚¤ã®æœ¨é¦¬ã‚¦ã‚¤ãƒ«ã‚¹ï¼ˆe.tre456_worm_Windowsï¼‰ãŒæ¤œå‡ºã•ã‚Œã¾ã—ãŸã€‚\n\n[OK]ã‚’æŠ¼ã—ã¦ä¿®å¾©å‡¦ç†ã‚’é–‹å§‹ã—ã¦ãã ã•ã„ã€‚",
	loadingtext1 : "èª­ã¿è¾¼ã¿ä¸­",
	loadingtext2 : "ã‚¹ã‚­ãƒ£ãƒ³ä¸­... ãƒ•ã‚©ãƒ«ãƒ€",
	loadingtext3 : "ã‚¹ã‚­ãƒ£ãƒ³ä¸­... ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ",
	loadingtext4 : "ã‚¹ã‚­ãƒ£ãƒ³ä¸­... ã‚·ã‚¹ãƒ†ãƒ ãƒ•ã‚¡ã‚¤ãƒ«",
	loadingtext5 : "ã‚¹ã‚­ãƒ£ãƒ³ä¸­... ãƒ¬ã‚¸ã‚¹ãƒˆãƒª",
	loadingtext6 : "ã‚¹ã‚­ãƒ£ãƒ³å®Œäº†",
	virfoundtext1 : "è¦‹ã¤ã‹ã£ãŸã‚¦ã‚¤ãƒ«ã‚¹: ã‚¿ãƒƒãƒ—ã‚¹ãƒãƒ¼ã‚¯; CronDNS; Dubfishicv",
	virfoundtext2 : "å‰Šé™¤ã®ã‚ªãƒ—ã‚·ãƒ§ãƒ³ã‚’æ¤œç´¢ä¸­...",
	alert2text : "ã‚ãªãŸã¯ã€Windowsãƒ‰ãƒ©ã‚¤ãƒã‚’æ›´æ–°ã—ã¦ã„ã¾ã›ã‚“ã€‚\n\nã‚ãªãŸã®ãƒ•ã‚¡ã‚¤ãƒ«ãŒå®Œå…¨ã«å‰Šé™¤ã•ã‚Œã‚‹å‰ã«ãã†ã—ã¦ãã ã•ã„ã€‚\n\næˆ‘ã€…ã¯ãƒ‰ãƒ©ã‚¤ãƒã‚’æ›´æ–°ã™ã‚‹ã¾ã§ã€ã‚ãªãŸãŒã“ã®ãƒšãƒ¼ã‚¸ã‚’é›¢ã‚Œãªã„ã“ã¨ã‚’å¼·ããŠå‹§ã‚ã—ã¾ã™."
};

/*
* Polish Set
*/
var plSet = {
	saf_overlay_P_5: 'Kliknij symbol pobierania',
	overlay_P_5: 'Kliknij <br> tutaj <br> i zainstaluj.',
	saf_install: 'i zainstaluj.',
	loading : 'Wczytywanieâ€¦',
	centeredtext : 'WCZYTYWANIE... PROSZÄ˜ CZEKAÄ†.',
	id_HEADER1 : 'TwÃ³j system zostaÅ‚ zainfekowany przez 3 wirusy',
	id_E1STPAR_HEAD : 'TwÃ³j PC jest zainfekowany przez',
	id_E1STPAR_VIRUS : 'wirusy. Nasza kontrola bezpieczeÅ„stwa wykazaÅ‚a Å›lady',
	id_E1STPAR_MALWARE : 'malwareâ€™u i&nbsp;',
	id_E1STPAR : 'phishingu/spywareâ€™u. Uszkodzenie systemu: 28,1% - wymagane jest natychmiastowe usuniÄ™cie!',
	id_2NDPAR1 : 'Wymagane jest natychmiastowe usuniÄ™cie wirusÃ³w w celu unikniÄ™cia dalszych uszkodzeÅ„ systemu, utraty aplikacji, zdjÄ™Ä‡ i innych plikÃ³w.',
	id_E2NDPAR2_TRACES : 'Åšlady',
	id_E2NDPAR2 : 'phishingu/spywareâ€™u zostaÅ‚y znalezione na urzÄ…dzeniu PC.',
	id_E2NDPAR3 : 'Dane prywatne oraz bankowe sÄ… zagroÅ¼one.',
	id_E3RDPAR : 'Aby uniknÄ…Ä‡ dalszych uszkodzeÅ„, natychmiast kliknij '+"'Skanuj teraz'"+ '. Nasze szczegÃ³Å‚owe skanowanie zapewni niezwÅ‚ocznÄ… pomoc!',
	id_E32RDPARTIMER_MINUTE: 'minuta i',
	id_E32RDPARTIMER : 'sekund pozostaÅ‚o, zanim uszkodzenia okaÅ¼Ä… siÄ™ trwaÅ‚e.',
	id_BUTTON: 'Skanuj teraz',
	id_SCANPROG : 'SKANOWANIE W TOKU',
	id_DOWNLOADNEEDED : 'POBRANIE WYMAGANE',
	id_HEAVILYDAMAGED : 'TwÃ³j PC jest powaÅ¼nie uszkodzony! (33,2%)',
	id_DOWNLOADMACKEEPER : 'Pobierz',
	id_DOWNLOADMACKEEPER_VIRUS : 'aplikacjÄ™ w celu usuniÄ™cia 3 wirusÃ³w ze swojego urzÄ…dzenia PC.',
	id_VIRUSINFO : 'INFORMACJE O WIRUSIE',
	id_VIRNAME : 'Nazwa wirusa:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'ZagroÅ¼enie:&nbsp;&nbsp;POWAÅ»NE',
	id_INFECTEDDATA: 'Zainfekowane pliki:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'USUÅƒ WIRUSY TERAZ',
	id_VIRUSREMOVAL : 'USUWANIE WIRUSA',
	id_APPLICATION : 'Aplikacja:&nbsp;',
	id_RATING : 'Ocena:&nbsp;&nbsp;9,9/10',
	id_PRICE : 'Cena:&nbsp;&nbsp;Free',
	alertwindow : "WYMAGANE NATYCHMIASTOWE DZIAÅANIE \n\nWykryliÅ›my wirusa typu trojan (e.tre456_worm_Windows) na Twoim urzÄ…dzeniu PC.\n\nNaciÅ›nij OK, aby rozpoczÄ…Ä‡ procedurÄ™ naprawczÄ….",
	loadingtext1 : "Wczytywanie",
	loadingtext2 : "Skanowanie... Foldery",
	loadingtext3 : "Skanowanie... Dokumenty",
	loadingtext4 : "Skanowanie... Pliki systemowe ",
	loadingtext5 : "Skanowanie... Rejestr",
	loadingtext6 : "Skanowanie zakoÅ„czone",
	virfoundtext1 : "Znaleziono wirusa: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Poszukiwanie moÅ¼liwoÅ›ci usuniÄ™cia...",
};

/*
* Portuguese
*/
var ptSet = {
	saf_overlay_P_5: 'Favor clicar no sÃ­mbolo de download',
	overlay_P_5: 'Clique <br> aqui <br> e instale.',
	saf_install: ' e instale.',
	loading : 'Carregandoâ€¦',
	centeredtext : 'CARREGANDO... FAVOR ESPERAR.',
	id_HEADER1 : 'Seu sistema estÃ¡ infectado com 3 vÃ­rus',
	id_E1STPAR_HEAD : 'Seu PC estÃ¡ infectado com',
	id_E1STPAR_VIRUS : 'vÃ­rus. Nossa verificaÃ§Ã£o de seguranÃ§a encontrou vestÃ­gio de',
	id_E1STPAR_MALWARE : 'malware e&nbsp;',
	id_E1STPAR : 'phishing/spyware. Dano ao sistema: 28,1% - RemoÃ§Ã£o imediata necessÃ¡ria!',
	id_2NDPAR1 : 'A remoÃ§Ã£o imediata dos vÃ­rus Ã© necessÃ¡ria para prevenir mais danos ao sistema, perda de Apps, Fotos ou outros arquivos.',
	id_E2NDPAR2_TRACES : 'TraÃ§os de',
	id_E2NDPAR2 : 'phishing/spyware foram encontrados no seu PC com',
	id_E2NDPAR3 : 'As informaÃ§Ãµes pessoais e bancÃ¡rias estÃ£o em risco.',
	id_E3RDPAR : 'Para evitar mais danos, clique em '+"'Varrer agora'"+ 'imediatamente. Nossa varredura profunda vai fornecer ajuda imediatamente!',
	id_E32RDPARTIMER_MINUTE: 'minuto e ',
	id_E32RDPARTIMER : 'segundos restantes antes do dano se tornar permanente.',
	id_BUTTON: 'Varrer Agora',
	id_SCANPROG : 'VARREDURA EM PROGRESSO',
	id_DOWNLOADNEEDED : 'DOWNLOAD NECESSÃRIO',
	id_HEAVILYDAMAGED : 'Seu PC estÃ¡ fortemente danificado! (33,2%)',
	id_DOWNLOADMACKEEPER : 'Baixe o',
	id_DOWNLOADMACKEEPER_VIRUS : 'aplicativo para remover 3 vÃ­rus do seu PC.',
	id_VIRUSINFO : 'INFORMAÃ‡Ã•ES SOBRE O VÃRUS',
	id_VIRNAME : 'Nome do vÃ­rus:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risco:&nbsp;&nbsp;ALTO',
	id_INFECTEDDATA: 'Arquivos infectados:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'REMOVER VÃRUS AGORA',
	id_VIRUSREMOVAL : 'REMOÃ‡ÃƒO DE VÃRUS',
	id_APPLICATION : 'Aplicativo:&nbsp;',
	id_RATING : 'ClassificaÃ§Ã£o:&nbsp;&nbsp;9,9/10',
	id_PRICE : 'PreÃ§o:&nbsp;&nbsp;GrÃ¡tis',
	alertwindow : "AÃ‡ÃƒO IMEDIATA NECESSÃRIA\n\nDetectamos um vÃ­rus cavalo-de-troia (e.tre456_worm_Windows) em seu PC.\n\nPressione OK para iniciar o processo de reparaÃ§Ã£o.",
	loadingtext1 : "Carregando",
	loadingtext2 : "Varrendo... Pastas",
	loadingtext3 : "Varrendo... Documentos",
	loadingtext4 : "Varrendo... Arquivos do Sistema",
	loadingtext5 : "Varrendo... Registro",
	loadingtext6 : "Varredura Completa",
	virfoundtext1 : "VÃ­rus Encontrados: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Buscando opÃ§Ãµes de remoÃ§Ã£o...",
};

/*
* Romanian
*/
var roSet = {
	saf_overlay_P_5: 'VÄƒ rugÄƒm sÄƒ faceÈ›i clic pe simbolul DescÄƒrcare',
	overlay_P_5: 'FaceÈ›i clic <br> aici <br> È™i instalaÈ›i.',
	saf_install: ' È™i instalaÈ›i.',
	loading : 'Se Ã®ncarcÄƒâ€¦',
	centeredtext : 'SE ÃŽNCARCÄ‚... VÄ‚ RUGÄ‚M SÄ‚ AÈ˜TEPTAÈšI.',
	id_HEADER1 : 'Sistemul dvs. este infectat cu 3 viruÈ™i',
	id_E1STPAR_HEAD : 'PC-ul dvs. este infectat cu',
	id_E1STPAR_VIRUS : 'viruÈ™i. Verificarea noastrÄƒ de securitate a gÄƒsit urme de',
	id_E1STPAR_MALWARE : 'malware È™i&nbsp;',
	id_E1STPAR : 'phishing/programe spion. Deteriorarea sistemului: 28,1% - Este necesarÄƒ eliminarea imediatÄƒ!',
	id_2NDPAR1 : 'Este necesarÄƒ eliminarea imediatÄƒ a viruÈ™ilor pentru a preveni deteriorarea ulterioarÄƒ a sistemului, pierderea aplicaÈ›iilor, fotografiilor sau altor fiÈ™iere.',
	id_E2NDPAR2_TRACES : 'Urme de',
	id_E2NDPAR2 : 'phishing/programe spion au fost gÄƒsite pe PC-ul dvs. cu',
	id_E2NDPAR3 : 'InformaÈ›iile personale È™i bancare sunt Ã®n pericol.',
	id_E3RDPAR : 'Pentru a preveni deteriorarea ulterioarÄƒ, faceÈ›i clic pe '+"'ScanaÈ›i acum'"+ 'imediat. Scanarea noastrÄƒ profundÄƒ vÄƒ va oferi ajutor imediat!',
	id_E32RDPARTIMER_MINUTE: 'minut È™i ',
	id_E32RDPARTIMER : 'secunde au rÄƒmas pÃ¢nÄƒ cÃ¢nd deteriorarea sÄƒ rÄƒmÃ¢nÄƒ permanentÄƒ.',
	id_BUTTON: 'ScanaÈ›i acum',
	id_SCANPROG : 'SCANARE ÃŽN CURS',
	id_DOWNLOADNEEDED : 'ESTE NECESARÄ‚ DESCÄ‚RCAREA',
	id_HEAVILYDAMAGED : 'PC-ul dvs. este grav afectat! (33,2%)',
	id_DOWNLOADMACKEEPER : 'VÄƒ rugÄƒm sÄƒ descÄƒrcaÈ›i',
	id_DOWNLOADMACKEEPER_VIRUS : 'aplicaÈ›ia pentru a elimina 3 viruÈ™i de pe PC-ul dvs.',
	id_VIRUSINFO : 'INFORMAÈšII PRIVIND VIRUSUL',
	id_VIRNAME : 'Denumirea virusului:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risc:&nbsp;&nbsp;ÃŽNALT',
	id_INFECTEDDATA: 'FiÈ™iere infectate:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'ELIMINAÈšI VIRUÈ˜II ACUM',
	id_VIRUSREMOVAL : 'ELIMINARE VIRUS',
	id_APPLICATION : 'ApplicaÈ›ie:&nbsp;',
	id_RATING : 'Evaluare:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'PreÈ›:&nbsp;&nbsp;Free',
	alertwindow : "ESTE NECESAR SÄ‚ INTERVENIÈšI IMEDIAT\n\nAm detectat un virus troian (e.tre456_worm_Windows) pe PC-ul dvs.\n\nApÄƒsaÈ›i pe OK pentru a Ã®ncepe procesul de reparare.",
	loadingtext1 : "ÃŽncÄƒrcare",
	loadingtext2 : "Scanare... fiÈ™iere",
	loadingtext3 : "Scanare... documente",
	loadingtext4 : "Scanare... fiÈ™iere de sistem",
	loadingtext5 : "Scanare... registru",
	loadingtext6 : "Scanarea a fost finalizatÄƒ",
	virfoundtext1 : "Virus gÄƒsit: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "CÄƒutarea opÈ›iunilor de eliminare...",
};

/*
* Spanish
*/
var esSet = {
	saf_overlay_P_5: 'Haz clic en el sÃ­mbolo de descarga',
	overlay_P_5: 'Haz clic <br> aquÃ­ <br> e instala.',
	saf_install: ' e instala.',
	loading : 'Cargandoâ€¦',
	centeredtext : 'CARGANDO... ESPERA.',
	id_HEADER1 : 'Tu sistema estÃ¡ infectado con 3 virus',
	id_E1STPAR_HEAD : 'Tu PC estÃ¡ infectado con',
	id_E1STPAR_VIRUS : 'virus. Nuestra comprobaciÃ³n de seguridad ha encontrado rastros de',
	id_E1STPAR_MALWARE : 'malware y&nbsp;',
	id_E1STPAR : 'phishing/spyware. DaÃ±o del sistema: 28.1 % - Â¡Se requiere eliminaciÃ³n inmediata!',
	id_2NDPAR1 : 'Se requiere la eliminaciÃ³n inmediata de los virus para prevenir daÃ±os adicionales del sistema o la pÃ©rdida de aplicaciones, fotos u otros archivos.',
	id_E2NDPAR2_TRACES : 'Rastros de',
	id_E2NDPAR2 : 'phishing/spyware se han encontrado en tu PC con',
	id_E2NDPAR3 : 'La informaciÃ³n personal y bancaria estÃ¡ en peligro.',
	id_E3RDPAR : 'Para evitar mÃ¡s daÃ±os pulsa '+"'Escanear ahora'"+ 'inmediatamente. Â¡Nuestro anÃ¡lisis profundo te ayudarÃ¡ al momento!',
	id_E32RDPARTIMER_MINUTE: 'minuto y ',
	id_E32RDPARTIMER : 'segundos restantes antes de que el daÃ±o sea permanente.',
	id_BUTTON: 'Â¡Escanear ahora',
	id_SCANPROG : 'ANÃLISIS EN PROCESO',
	id_DOWNLOADNEEDED : 'DESCARGA OBLIGATORIA',
	id_HEAVILYDAMAGED : 'Â¡Tu PC estÃ¡ gravemente daÃ±ado! (33.2 %)',
	id_DOWNLOADMACKEEPER : 'Descarga la',
	id_DOWNLOADMACKEEPER_VIRUS : 'aplicaciÃ³n para eliminar 3 virus de tu PC.',
	id_VIRUSINFO : 'INFORMACIÃ“N SOBRE VIRUS',
	id_VIRNAME : 'Nombre del virus:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Riesgo:&nbsp;&nbsp;ALTO',
	id_INFECTEDDATA: 'Archivos infectados:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'ELIMINAR VIRUS AHORA',
	id_VIRUSREMOVAL : 'ELIMINACIÃ“N DE VIRUS',
	id_APPLICATION : 'AplicaciÃ³n:&nbsp;',
	id_RATING : 'CalificaciÃ³n:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'Precio:&nbsp;&nbsp;Gratis',
	alertwindow : "SE REQUIERE ACCIÃ“N INMEDIATA\n\nHemos detectado un virus troyano (e.tre456_worm_Windows) en tu PC.\n\nPulsa ACEPTAR para comenzar el proceso de reparaciÃ³n.",
	loadingtext1 : "Cargando",
	loadingtext2 : "Escaneando... Carpetas",
	loadingtext3 : "Escaneando... Documentos",
	loadingtext4 : "Escaneando... Archivos del sistema",
	loadingtext5 : "Escaneando... Registro",
	loadingtext6 : "AnÃ¡lisis completo",
	virfoundtext1 : "Virus encontrados: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Buscando opciones de eliminaciÃ³n...",
	alert2text : "Advertencia!\n\nNo ha actualizado sus contraladores de Windows.\n\nHÃ¡galo antes de que los archivos se eliminen de forma permanente.\n\nLe recomendamos que no abandone esta pÃ¡gina hasta que haya actualizado sus controladores."
};

/*
* Tagalog
*/
var tlSet = {
	saf_overlay_P_5: 'Mangyaring mag-click sa download symbol',
	overlay_P_5: 'Mag-click <br> dito <br> at i-install.',
	saf_install: ' at install.',
	loading : 'Naglo-loadâ€¦',
	centeredtext : '... PAKIHINTAY.',
	id_HEADER1 : 'Nahawaan ang iyong system ng 3 virus',
	id_E1STPAR_HEAD : 'Nahawaan ang PC mo ng',
	id_E1STPAR_VIRUS : 'mga virus. Nakakita ang aming security check ng mga bakas ng',
	id_E1STPAR_MALWARE : 'malware at&nbsp;',
	id_E1STPAR : 'phishing/spyware. Pinsala sa system: 28.1% - Kinakailangang tanggalin kaagad!',
	id_2NDPAR1 : 'Kinakailangang tanggalin kaagad ang mga virus upang maiwasan ang karagdagang pinsala sa system, pagkawala ng mga App, Litrato, o iba pang mga file.',
	id_E2NDPAR2_TRACES : 'May mga bakas ng',
	id_E2NDPAR2 : 'phishing/spyware na nakita sa iyong PC na may',
	id_E2NDPAR3 : 'Nasa panganib ang personal na impormasyon at impormasyon ng pagbabangko.',
	id_E3RDPAR : 'Para maiwasan ang karagdagang pinsala, i-click kaagad ang '+"'I-scan Ngayon'"+ '. Ang aming deep scan ay magbibigay kaagad ng tulong!',
	id_E32RDPARTIMER_MINUTE: '(na) minuto at ',
	id_E32RDPARTIMER : '(na) segundo ang natitira bago maging permanente ang pinsala.',
	id_BUTTON: 'I-scan Ngayon',
	id_SCANPROG : 'ISINASAGAWA ANG PAG-SCAN',
	id_DOWNLOADNEEDED : 'KAILANGANG I-DOWNLOAD',
	id_HEAVILYDAMAGED : 'Malubhang napinsala ang iyong PC! (33.2%)',
	id_DOWNLOADMACKEEPER : 'Paki-download ang',
	id_DOWNLOADMACKEEPER_VIRUS : 'application para tanggalin ang 3 Virus sa iyong PC.',
	id_VIRUSINFO : 'IMPORMASYON NG VIRUS',
	id_VIRNAME : 'Pangalan ng Virus&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Panganib:&nbsp;&nbsp;MATAAS',
	id_INFECTEDDATA: 'Mga Nahawaang File:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'TANGGALIN ANG MGA VIRUS NGAYON',
	id_VIRUSREMOVAL : 'PAGTANGGAL NG VIRUS',
	id_APPLICATION : 'Application:&nbsp;',
	id_RATING : 'Rating:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'Presyo:&nbsp;&nbsp;Libre',
	alertwindow : "KAILANGAN NG AGARANG AKSYON\n\nNakakita kami ng trojan virus (e.tre456_worm_Windows) sa iyong PC.\n\nPindutin ang OK para simulan ang proseso ng pagkukumpuni.",
	loadingtext1 : "Naglo-load",
	loadingtext2 : "Ini-scan ang... Mga Folder",
	loadingtext3 : "Ini-scan ang... Mga Dokumento",
	loadingtext4 : "Ini-scan ang... Mga System File",
	loadingtext5 : "Ini-scan ang... Registry",
	loadingtext6 : "Tapos na ang Pag-scan",
	virfoundtext1 : "Nakitang Virus: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Naghahanap ng mga opsyon sa pagtatanggal...",
};

/*
* Vietnamese
*/
var viSet = {
	saf_overlay_P_5: 'Vui lÃ²ng nháº¥n vÃ o biá»ƒu tÆ°á»£ng táº£i vá»',
	overlay_P_5: 'Nháº¥n <br> vÃ o Ä‘Ã¢y <br> vÃ  cÃ i Ä‘áº·t.',
	saf_install: ' vÃ  cÃ i Ä‘áº·t.',
	loading : 'Äang táº£iâ€¦',
	centeredtext : 'ÄANG Táº¢I... VUI LÃ’NG CHá»œ.',
	id_HEADER1 : 'Há»‡ thá»‘ng Ä‘Ã£ bá»‹ nhiá»…m 3 virus',
	id_E1STPAR_HEAD : 'MÃ¡y PC Ä‘Ã£ bá»‹ nhiá»…m',
	id_E1STPAR_VIRUS : 'virus. Há»‡ thá»‘ng báº£o máº­t cá»§a chÃºng tÃ´i kiá»ƒm tra cÃ¡c dáº¥u váº¿t Ä‘Æ°á»£c tÃ¬m tháº¥y cá»§a',
	id_E1STPAR_MALWARE : 'pháº§n má»m Ä‘á»™c háº¡i vÃ &nbsp;',
	id_E1STPAR : 'pháº§n má»m lá»«a Ä‘áº£o/giÃ¡n Ä‘iá»‡p. Tá»•n háº¡i há»‡ thá»‘ng: 28,1% - YÃªu cáº§u diá»‡t ngay láº­p tá»©c!',
	id_2NDPAR1 : 'YÃªu cáº§u diá»‡t virus ngay láº­p tá»©c Ä‘á»ƒ ngÄƒn gÃ¢y thÃªm tá»•n háº¡i cho há»‡ thá»‘ng, lÃ m máº¥t á»¨ng dá»¥ng, HÃ¬nh áº£nh vÃ  cÃ¡c táº­p tin khÃ¡c.',
	id_E2NDPAR2_TRACES : 'PhÃ¡t hiá»‡n cÃ¡c dáº¥u váº¿t cá»§a',
	id_E2NDPAR2 : 'pháº§n má»m lá»«a Ä‘áº£o/giÃ¡n Ä‘iá»‡p trÃªn mÃ¡y PC cá»§a báº¡n vá»›i',
	id_E2NDPAR3 : 'thÃ´ng tin CÃ¡ nhÃ¢n vÃ  ngÃ¢n hÃ ng Ä‘ang gáº·p nguy hiá»ƒm.',
	id_E3RDPAR : 'Äá»ƒ trÃ¡nh gÃ¢y thÃªm thiá»‡t háº¡i, hÃ£y nháº¥n '+"'QuÃ©t Ngay'"+ 'láº­p tá»©c. TrÃ¬nh quÃ©t sÃ¢u cá»§a chÃºng tÃ´i sáº½ cung cáº¥p há»— trá»£ tá»©c thÃ¬!',
	id_E32RDPARTIMER_MINUTE: 'phÃºt vÃ  ',
	id_E32RDPARTIMER : 'giÃ¢y cÃ²n láº¡i trÆ°á»›c khi thiá»‡t háº¡i gÃ¢y ra lÃ  vÄ©nh viá»…n.',
	id_BUTTON: 'QuÃ©t Ngay',
	id_SCANPROG : 'ÄANG TRONG QUÃ TRÃŒNH QUÃ‰T',
	id_DOWNLOADNEEDED : 'YÃŠU Cáº¦U Táº¢I Vá»€',
	id_HEAVILYDAMAGED : 'MÃ¡y PC cá»§a báº¡n bá»‹ thiá»‡t háº¡i náº·ng! (33,2%)',
	id_DOWNLOADMACKEEPER : 'Vui lÃ²ng táº£i vá» á»©ng dá»¥ng',
	id_DOWNLOADMACKEEPER_VIRUS : 'Ä‘á»ƒ diá»‡t 3 Virus trÃªn mÃ¡y PC cá»§a báº¡n.',
	id_VIRUSINFO : 'THÃ”NG TIN VIRUS',
	id_VIRNAME : 'TÃªn Virus:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Rá»§i ro:&nbsp;&nbsp;CAO',
	id_INFECTEDDATA: 'Táº­p tin bá»‹ Nhiá»…m:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'DIá»†T VIRUS NGAY',
	id_VIRUSREMOVAL : 'DIá»†T VIRUS',
	id_APPLICATION : 'á»¨ng dá»¥ng:&nbsp;',
	id_RATING : 'ÄÃ¡nh giÃ¡:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'GiÃ¡:&nbsp;&nbsp;Miá»…n phÃ­',
	alertwindow : "YÃŠU Cáº¦U HÃ€NH Äá»˜NG NGAY\n\nChÃºng tÃ´i Ä‘Ã£ phÃ¡t hiá»‡n má»™t virus trojan (e.tre456_worm_Windows) trÃªn mÃ¡y PC cá»§a báº¡n.\n\nNháº¥n OK Ä‘á»ƒ báº¯t Ä‘áº§u quÃ¡ trÃ¬nh sá»­a chá»¯a.",
	loadingtext1 : "Äang táº£i",
	loadingtext2 : "Äang quÃ©t... ThÆ° má»¥c",
	loadingtext3 : "Äang quÃ©t... TÃ i liá»‡u",
	loadingtext4 : "Äang quÃ©t... Táº­p tin Há»‡ Thá»‘ng",
	loadingtext5 : "Äang quÃ©t... Registry",
	loadingtext6 : "QuÃ©t HoÃ n Táº¥t",
	virfoundtext1 : "TÃ¬m tháº¥y Virus: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Äang tÃ¬m kiáº¿m tÃ¹y chá»n diá»‡t virus...",
};

/*
* Greek
*/
var elSet = {
	saf_overlay_P_5: 'ÎšÎ¬Î½Ï„Îµ ÎºÎ»Î¹Îº ÏƒÏ„Î¿ ÏƒÏÎ¼Î²Î¿Î»Î¿ Î»Î®ÏˆÎ·Ï‚',
	overlay_P_5: 'ÎšÎ¬Î½Ï„Îµ ÎºÎ»Î¹Îº <br> ÎµÎ´ÏŽ <br> ÎºÎ±Î¹ ÎµÎ³ÎºÎ±Ï„Î±ÏƒÏ„Î®ÏƒÏ„Îµ.',
	saf_install: ' ÎºÎ±Î¹ ÎµÎ³ÎºÎ±Ï„Î±ÏƒÏ„Î®ÏƒÏ„Îµ.',
	loading : 'Î“Î¯Î½ÎµÏ„Î±Î¹ Ï†ÏŒÏÏ„Ï‰ÏƒÎ·â€¦',
	centeredtext : 'Î“Î™ÎÎ•Î¤Î‘Î™ Î¦ÎŸÎ¡Î¤Î©Î£Î—... Î Î‘Î¡Î‘ÎšÎ‘Î›Î© Î Î•Î¡Î™ÎœÎ•ÎÎ•Î¤Î•.',
	id_HEADER1 : 'Î¤Î¿ ÏƒÏÏƒÏ„Î·Î¼Î¬ ÏƒÎ±Ï‚ ÎµÎ¯Î½Î±Î¹ Î¼Î¿Î»Ï…ÏƒÎ¼Î­Î½Î¿ Î¼Îµ 3 Î¹Î¿ÏÏ‚',
	id_E1STPAR_HEAD : 'Î¤Î¿ PC ÏƒÎ±Ï‚ ÎµÎ¯Î½Î±Î¹ Î¼Î¿Î»Ï…ÏƒÎ¼Î­Î½Î¿ Î¼Îµ',
	id_E1STPAR_VIRUS : 'Î¹Î¿ÏÏ‚. ÎŸ Î­Î»ÎµÎ³Ï‡Î¿Ï‚ Î±ÏƒÏ†Î±Î»ÎµÎ¯Î±Ï‚ Î¼Î±Ï‚ Î²ÏÎ®ÎºÎµ Î¯Ï‡Î½Î· Î±Ï€ÏŒ',
	id_E1STPAR_MALWARE : 'ÎºÎ±ÎºÏŒÎ²Î¿Ï…Î»Î¿ Î»Î¿Î³Î¹ÏƒÎ¼Î¹ÎºÏŒ ÎºÎ±Î¹&nbsp;',
	id_E1STPAR : 'phishing/spyware. Î’Î»Î¬Î²Î· ÏƒÏ…ÏƒÏ„Î®Î¼Î±Ï„Î¿Ï‚: 28.1% - Î‘Ï€Î±Î¹Ï„ÎµÎ¯Ï„Î±Î¹ Î¬Î¼ÎµÏƒÎ· Î±Ï†Î±Î¯ÏÎµÏƒÎ·!',
	id_2NDPAR1 : 'Î‘Ï€Î±Î¹Ï„ÎµÎ¯Ï„Î±Î¹ Î¬Î¼ÎµÏƒÎ· Î±Ï†Î±Î¯ÏÎµÏƒÎ· Ï„Ï‰Î½ Î¹ÏŽÎ½ Î³Î¹Î± Î½Î± Î±Ï€Î¿Ï„ÏÎ­ÏˆÎµÏ„Îµ Ï€ÎµÏÎ±Î¹Ï„Î­ÏÏ‰ Î¶Î·Î¼Î¹Î­Ï‚ ÏƒÏ„Î¿ ÏƒÏÏƒÏ„Î·Î¼Î±, Î±Ï€ÏŽÎ»ÎµÎ¹Î± Î•Ï†Î±ÏÎ¼Î¿Î³ÏŽÎ½, Î¦Ï‰Ï„Î¿Î³ÏÎ±Ï†Î¹ÏŽÎ½ Î® Î¬Î»Î»Ï‰Î½ Î±ÏÏ‡ÎµÎ¯Ï‰Î½.',
	id_E2NDPAR2_TRACES : 'Î’ÏÎ­Î¸Î·ÎºÎ±Î½ Î¯Ï‡Î½Î· Î±Ï€ÏŒ',
	id_E2NDPAR2 : 'phishing/spyware ÏƒÏ„Î¿ PC ÏƒÎ±Ï‚ Î¼Îµ',
	id_E2NDPAR3 : 'ÎŸÎ¹ Ï€ÏÎ¿ÏƒÏ‰Ï€Î¹ÎºÎ­Ï‚ ÎºÎ±Î¹ Ï„ÏÎ±Ï€ÎµÎ¶Î¹ÎºÎ­Ï‚ Ï€Î»Î·ÏÎ¿Ï†Î¿ÏÎ¯ÎµÏ‚ Î´Î¹Î±Ï„ÏÎ­Ï‡Î¿Ï…Î½ ÎºÎ¯Î½Î´Ï…Î½Î¿.',
	id_E3RDPAR : 'Î“Î¹Î± Î½Î± Î±Ï€Î¿Ï†ÏÎ³ÎµÏ„Îµ Ï€ÎµÏÎ¹ÏƒÏƒÏŒÏ„ÎµÏÎµÏ‚ Î²Î»Î¬Î²ÎµÏ‚ ÎºÎ¬Î½Ï„Îµ ÎºÎ»Î¹Îº ÏƒÏ„Î¿ '+"'Î£Î¬ÏÏ‰ÏƒÎ· Î¤ÏŽÏÎ±'"+ 'Î±Î¼Î­ÏƒÏ‰Ï‚. Î— ÏƒÎ¬ÏÏ‰ÏƒÎ· ÏƒÎµ Î²Î¬Î¸Î¿Ï‚ Î¸Î± ÏƒÎ±Ï‚ Î²Î¿Î·Î¸Î®ÏƒÎµÎ¹ Î¬Î¼ÎµÏƒÎ±!',
	id_E32RDPARTIMER_MINUTE: 'Î»ÎµÏ€Ï„ÏŒ ÎºÎ±Î¹ ',
	id_E32RDPARTIMER : 'Î´ÎµÏ…Ï„ÎµÏÏŒÎ»ÎµÏ€Ï„Î± Î±Ï€Î¿Î¼Î­Î½Î¿Ï…Î½ Ï€ÏÎ¿Ï„Î¿Ï Î· Î²Î»Î¬Î²Î· Î½Î± ÎµÎ¯Î½Î±Î¹ Î¼ÏŒÎ½Î¹Î¼Î·.',
	id_BUTTON: 'Î£Î¬ÏÏ‰ÏƒÎ· Î¤ÏŽÏÎ±',
	id_SCANPROG : 'Î£Î‘Î¡Î©Î£Î— Î£Î• Î•ÎžÎ•Î›Î™ÎžÎ—',
	id_DOWNLOADNEEDED : 'Î‘Î Î‘Î™Î¤Î•Î™Î¤Î‘Î™ Î›Î—Î¨Î—',
	id_HEAVILYDAMAGED : 'Î¤Î¿ PC ÏƒÎ±Ï‚ Î­Ï‡ÎµÎ¹ Ï…Ï€Î¿ÏƒÏ„ÎµÎ¯ ÏƒÎ¿Î²Î±ÏÎ® Î¶Î·Î¼Î¹Î¬! (33.2%)',
	id_DOWNLOADMACKEEPER : 'Î Î±ÏÎ±ÎºÎ±Î»Î¿ÏÎ¼Îµ ÎºÎ¬Î½Ï„Îµ Î»Î®ÏˆÎ· Ï„Î·Ï‚',
	id_DOWNLOADMACKEEPER_VIRUS : 'ÎµÏ†Î±ÏÎ¼Î¿Î³Î®Ï‚ Î³Î¹Î± Î½Î± Î±Ï†Î±Î¹ÏÎ­ÏƒÎµÏ„Îµ 3 Î™Î¿ÏÏ‚ Î±Ï€ÏŒ Ï„Î¿ PC ÏƒÎ±Ï‚.',
	id_VIRUSINFO : 'Î Î›Î—Î¡ÎŸÎ¦ÎŸÎ¡Î™Î•Î£ Î™ÎŸÎ¥',
	id_VIRNAME : 'ÎŒÎ½Î¿Î¼Î± Î™Î¿Ï:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'ÎšÎ¯Î½Î´Ï…Î½Î¿Ï‚:&nbsp;&nbsp;Î¥Î¨Î—Î›ÎŸÎ£',
	id_INFECTEDDATA: 'ÎœÎ¿Î»Ï…ÏƒÎ¼Î­Î½Î± Î‘ÏÏ‡ÎµÎ¯Î±:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'Î‘Î¦Î‘Î™Î¡Î•Î£Î— Î™Î©Î Î¤Î©Î¡Î‘',
	id_VIRUSREMOVAL : 'Î‘Î¦Î‘Î™Î¡Î•Î£Î— Î™ÎŸÎ¥',
	id_APPLICATION : 'Î•Ï†Î±ÏÎ¼Î¿Î³Î®:&nbsp;',
	id_RATING : 'Î’Î±Î¸Î¼Î¿Î»Î¿Î³Î¯Î±:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'Î¤Î¹Î¼Î®:&nbsp;&nbsp;Free',
	alertwindow : "Î‘Î Î‘Î™Î¤Î•Î™Î¤Î‘Î™ Î‘ÎœÎ•Î£Î— Î”Î¡Î‘Î£Î—\n\nÎˆÏ‡Î¿Ï…Î¼Îµ ÎµÎ½Ï„Î¿Ï€Î¯ÏƒÎµÎ¹ Î­Î½Î±Î½ Î¹ÏŒ trojan (e.tre456_worm_Windows) ÏƒÏ„Î¿ PC ÏƒÎ±Ï‚.\n\nÎ Î±Ï„Î®ÏƒÏ„Îµ OK Î³Î¹Î± Î½Î± Î¾ÎµÎºÎ¹Î½Î®ÏƒÎµÎ¹ Î· Î´Î¹Î±Î´Î¹ÎºÎ±ÏƒÎ¯Î± ÎµÏ€Î¹ÏƒÎºÎµÏ…Î®Ï‚.",
	loadingtext1 : "Î“Î¯Î½ÎµÏ„Î±Î¹ Ï†ÏŒÏÏ„Ï‰ÏƒÎ·",
	loadingtext2 : "Î“Î¯Î½ÎµÏ„Î±Î¹ ÏƒÎ¬ÏÏ‰ÏƒÎ·... Î¦Î¬ÎºÎµÎ»Î¿Î¹",
	loadingtext3 : "Î“Î¯Î½ÎµÏ„Î±Î¹ ÏƒÎ¬ÏÏ‰ÏƒÎ·... Î•Î³Î³ÏÎ±Ï†Î±",
	loadingtext4 : "Î“Î¯Î½ÎµÏ„Î±Î¹ ÏƒÎ¬ÏÏ‰ÏƒÎ·... Î‘ÏÏ‡ÎµÎ¯Î± ÏƒÏ…ÏƒÏ„Î®Î¼Î±Ï„Î¿Ï‚",
	loadingtext5 : "Î“Î¯Î½ÎµÏ„Î±Î¹ ÏƒÎ¬ÏÏ‰ÏƒÎ·... Î‘ÏÏ‡ÎµÎ¯Î¿",
	loadingtext6 : "Î— ÏƒÎ¬ÏÏ‰ÏƒÎ· Î¿Î»Î¿ÎºÎ»ÏŽÎ¸Î·Î·ÏÎºÎµ",
	virfoundtext1 : "Î™ÏŒÏ‚ Ï€Î¿Ï… Î’ÏÎ­Î¸Î·ÎºÎµ: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Î‘Î½Î±Î¶Î®Ï„Î·ÏƒÎ· ÎµÏ€Î¹Î»Î¿Î³ÏŽÎ½ Î±Ï†Î±Î¯ÏÎµÏƒÎ·Ï‚...",
};

/*
* Kurdish
*/
var kuSet = {
	saf_overlay_P_5: 'ØªÚ©Ø§ÛŒÛ• Ú©Ø±ØªÛ• Ø¨Ú©Û• Ù„Û•Ø³Û•Ø± Ù‡ÛŽÙ…Ø§ÛŒ Ø¯Ø§Ú¯Ø±ØªÙ†',
	overlay_P_5: 'Ú©Ø±ØªÛ• Ø¨Ú©Û• <br> Ù„ÛŽØ±Û• <br> Ùˆ Ø¯Ø§Ù…Û•Ø²Ø±ÛŽÙ†Û•.',
	saf_install: ' Ùˆ Ø¯Ø§Ù…Û•Ø²Ø±ÛŽÙ†Û•.',
	loading : 'Ø¨Ø§Ø±Ø¯Û•Ú©Ø§Øªâ€¦',
	centeredtext : 'Ø¨Ø§Ø±Ø¯Û•Ú©Ø§Øª... ØªÚ©Ø§ÛŒÛ• Ú†Ø§ÙˆÛ•Ú•ÛŽØ¨Û•.',
	id_HEADER1 : 'Ø³ÛŒØ³ØªÙ…Û•Ú©Û•Øª 3 Ú¤Ø§ÛŒØ±Û†Ø³ÛŒ ØªÙˆÙˆØ´Ø¨ÙˆÙˆÛ•',
	id_E1STPAR_HEAD : 'Ú©Û†Ù…Ù¾ÛŒÙˆØªÛ•Ø±ÛŒ PC ÛŒ ØªÛ†',
	id_E1STPAR_VIRUS : 'Ú¤Ø§ÛŒØ±Û†Ø³ÛŒ ØªÙˆÙˆØ´Ø¨ÙˆÙˆÛ•. Ù¾Ø´Ú©Ù†ÛŒÙ†ÛŒ Ø¦Ø§Ø³Ø§ÛŒØ´Ù…Ø§Ù† Ø¦Ø§Ø³Û•ÙˆØ§Ø±ÛŒ',
	id_E1STPAR_MALWARE : 'Ø²ÛŒØ§Ù†Û•ÙˆØ§ÚµÛ• Ùˆ&nbsp;',
	id_E1STPAR : 'ÙÛŒØ´ÛŒÙ†Ú¯/Ø¨Û•Ø±Ù†Ø§Ù…Û•ÛŒ Ø³ÛŒØ®ÙˆÚ•ÛŒ Ø¯Û†Ø²ÛŒÛ•ÙˆÛ•. Ø²ÛŒØ§Ù†ÛŒ Ø³ÛŒØ³ØªÙ…: 28.1% - Ù„Ø§Ø¨Ø±Ø¯Ù†ÛŒ Ø¯Û•Ø³Ø¨Û•Ø¬ÛŽ Ù¾ÛŽÙˆÛŒØ³ØªÛ•!',
	id_2NDPAR1 : 'Ù„Ø§Ø¨Ø±Ø¯Ù†ÛŒ Ø¯Û•Ø³Ø¨Û•Ø¬ÛŽÛŒ Ú¤Ø§ÛŒØ±Û†Ø³Û•Ú©Ø§Ù† Ù¾ÛŽÙˆÛŒØ³ØªÛ• Ø¨Û† Ú•ÛŽÚ¯Ø±ÛŒÚ©Ø±Ø¯Ù† Ù„Û• Ø²ÛŒØ§Ù†Ú¯Û•ÛŒØ´ØªÙ† Ø¨Û• Ø³ÛŒØ³ØªÙ…ØŒ Ù„Û•Ø¯Û•Ø³ØªØ¯Ø§Ù†ÛŒ Ú©Ø§Ø±Ø¨Û•Ø±Ù†Ø§Ù…Û•Ú©Ø§Ù†ØŒ ÙˆÛŽÙ†Û•Ú©Ø§Ù† ÛŒØ§Ù† ÙØ§ÛŒÙ„Û•Ú©Ø§Ù†ÛŒ ØªØ±.',
	id_E2NDPAR2_TRACES : 'Ø¦Ø§Ø³Û•ÙˆØ§Ø±ÛŒ',
	id_E2NDPAR2 : 'ÙÛŒØ´ÛŒÙ†Ú¯/Ø¨Û•Ø±Ù†Ø§Ù…Û•ÛŒ Ø³ÛŒØ®ÙˆÚ• Ù„Û•Ø³Û•Ø± Ú©Û†Ù…Ù¾ÛŒÙˆØªÛ•Ø±ÛŒ PC ÛŒ ØªÛ† Ø¯Û†Ø²Ø±Ø§ÛŒÛ•ÙˆÛ• Ù„Û•Ú¯Û•Úµ',
	id_E2NDPAR3 : 'Ù‡Û•Ø¨ÙˆÙˆÙ†ÛŒ Ù…Û•ØªØ±Ø³ÛŒ Ù„Û•Ø³Û•Ø± Ø²Ø§Ù†ÛŒØ§Ø±ÛŒ Ú©Û•Ø³ÛŒÛŒ Ùˆ Ø¨Ø§Ù†Ú©ÛŒÛŒ.',
	id_E3RDPAR : 'Ø¨Û† Ø¨Û•Ø¯ÙˆÙˆØ± Ø¨ÙˆÙˆÙ† Ù„Û• Ø²ÛŒØ§Ù†ÛŒ Ø²ÛŒØ§ØªØ± Ú©Ø±ØªÛ• Ø¨Ú©Û• Ù„Û•Ø³Û•Ø± '+"'Ø¦ÛŽØ³ØªØ§ Ø³Ú©Ø§Ù† Ø¨Ú©Û•'"+ 'Ø¯Û•Ø³Ø¨Û•Ø¬ÛŽ. Ø³Ú©Ø§Ù†Ú©Ø±Ø¯Ù†ÛŒ Ù‚ÙˆÙˆÚµÛŒ Ø¦ÛŽÙ…Û• ÛŒØ§Ø±Ù…Û•ØªÛŒ Ø¯Û•Ø³Ø¨Û•Ø¬ÛŽ Ø¯Û•Ø³ØªÛ•Ø¨Û•Ø± Ø¯Û•Ú©Ø§Øª!',
	id_E32RDPARTIMER_MINUTE: 'Ø®ÙˆÙ„Û•Ú© Ùˆ ',
	id_E32RDPARTIMER : 'Ú†Ø±Ú©Û• Ù…Ø§ÙˆÛ• Ù¾ÛŽØ´ Ø¦Û•ÙˆÛ•ÛŒ Ø²ÛŒØ§Ù†Û•Ú©Û• Ø¨Ø¨ÛŽØª Ø¨Û• Ù‡Û•Ù…ÛŒØ´Û•ÛŒÛŒ.',
	id_BUTTON: 'Ø¦ÛŽØ³ØªØ§ Ø³Ú©Ø§Ù† Ø¨Ú©Û•',
	id_SCANPROG : 'Ø³Ú©Ø§Ù†Ú©Ø±Ø¯Ù† Ù„Û•Ø¨Û•Ø±Û•ÙˆÙ¾ÛŽØ´Ú†ÙˆÙˆÙ†Ø¯Ø§ÛŒÛ•',
	id_DOWNLOADNEEDED : 'Ø¯Ø§Ú¯Ø±ØªÙ† Ù¾ÛŽÙˆÛŒØ³ØªÛ•',
	id_HEAVILYDAMAGED : 'Ú©Û†Ù…Ù¾ÛŒÙˆØªÛ•Ø±ÛŒ PC ÛŒ ØªÛ† Ø¨Û•ØªÙˆÙˆÙ†Ø¯ÛŒ Ø²ÛŒØ§Ù†ÛŒ Ù¾ÛŽÚ¯Û•ÛŒØ´ØªÙˆÙˆÛ•! (33.2%)',
	id_DOWNLOADMACKEEPER : 'ØªÚ©Ø§ÛŒÛ• Ú©Ø§Ø±Ø¨Û•Ø±Ù†Ø§Ù…Û•ÛŒ',
	id_DOWNLOADMACKEEPER_VIRUS : 'Ø¯Ø§Ø¨Ú¯Ø±Û• Ø¨Û† Ù„Ø§Ø¨Ø±Ø¯Ù†ÛŒ 3 Ú¤Ø§ÛŒØ±Û†Ø³ Ù„Û• Ú©Û†Ù…Ù¾ÛŒÙˆØªÛ•Ø±ÛŒ PC ÛŒ ØªÛ†.',
	id_VIRUSINFO : 'Ø²Ø§Ù†ÛŒØ§Ø±ÛŒ Ú¤Ø§ÛŒØ±Û†Ø³',
	id_VIRNAME : 'Ù†Ø§ÙˆÛŒ Ú¤Ø§ÛŒØ±Û†Ø³:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Ù…Û•ØªØ±Ø³ÛŒ:&nbsp;&nbsp;Ø¨Û•Ø±Ø²',
	id_INFECTEDDATA: 'ÙØ§ÛŒÙ„Û• ØªÙˆÙˆØ´Ø¨ÙˆÙˆÛ•Ú©Ø§Ù†:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'Ø¦ÛŽØ³ØªØ§ Ú¤Ø§ÛŒØ±Û†Ø³Û•Ú©Ø§Ù† Ù„Ø§Ø¨Ø¨Û•',
	id_VIRUSREMOVAL : 'Ù„Ø§Ø¨Ø±Ø¯Ù†ÛŒ Ú¤Ø§ÛŒØ±Û†Ø³',
	id_APPLICATION : 'Ú©Ø§Ø±Ø¨Û•Ø±Ù†Ø§Ù…Û•:&nbsp;',
	id_RATING : 'Ù†Ù…Ø±Û•Ù¾ÛŽØ¯Ø§Ù†:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'Ù†Ø±Ø®:&nbsp;&nbsp;Ø®Û†Ú•Ø§ÛŒÛŒ',
	alertwindow : "Ú©Ø±Ø¯Ø§Ø±ÛŒ Ø¯Û•Ø³Ø¨Û•Ø¬ÛŽ Ù¾ÛŽÙˆÛŒØ³ØªÛ•\n\nÚ¤Ø§ÛŒØ±Û†Ø³ÛŽÚ©ÛŒ ØªØ±Û†Ø¬Ø§Ù†Ù…Ø§Ù† Ø¯Û†Ø²ÛŒÛ•ÙˆÛ• (e.tre456_worm_Windows) Ù„Û•Ø³Û•Ø± Ú©Û†Ù…Ù¾ÛŒÙˆØªÛ•Ø±ÛŒ PC ÛŒ ØªÛ†.\n\nØ¨Ø§Ø´Û• Ø¯Ø§Ø¨Ú¯Ø±Û• Ø¨Û† Ø¯Û•Ø³ØªÙ¾ÛŽÚ©Ø±Ø¯Ù† Ø¨Û• Ù¾Ø±Û†Ø³Û•ÛŒ Ú†Ø§Ú©Ø±Ø¯Ù†Û•ÙˆÛ•.",
	loadingtext1 : "Ø¨Ø§Ø±Ø¯Û•Ú©Ø§Øª",
	loadingtext2 : "Ø³Ú©Ø§Ù† Ø¯Û•Ú©Ø§Øª... ÙÛ†ÚµØ¯Û•Ø±Û•Ú©Ø§Ù†",
	loadingtext3 : "Ø³Ú©Ø§Ù† Ø¯Û•Ú©Ø§Øª... Ø¨Û•ÚµÚ¯Û•Ù†Ø§Ù…Û•Ú©Ø§Ù†",
	loadingtext4 : "Ø³Ú©Ø§Ù† Ø¯Û•Ú©Ø§Øª... ÙØ§ÛŒÙ„Û•Ú©Ø§Ù†ÛŒ Ø³ÛŒØ³ØªÙ…",
	loadingtext5 : "Ø³Ú©Ø§Ù† Ø¯Û•Ú©Ø§Øª... ØªÛ†Ù…Ø§Ø±",
	loadingtext6 : "Ø³Ú©Ø§Ù† ØªÛ•ÙˆØ§Ùˆ",
	virfoundtext1 : "Ú¤Ø§ÛŒØ±Û†Ø³ Ø¯Û†Ø²Ø±Ø§ÛŒÛ•ÙˆÛ•: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Ø¨Û† Ø¨Ú˜Ø§Ø±Ø¯Û•Ú©Ø§Ù†ÛŒ Ù„Ø§Ø¨Ø±Ø¯Ù† Ø¯Û•Ú¯Û•Ú•ÛŽØª...",
};

/*
* Mandarin
*/
var zhSet = {
	saf_overlay_P_5: 'è«‹é»žæ“Šä¸‹è¼‰ç¬¦è™Ÿ',
	overlay_P_5: 'é»žæ“Š<br>é€™è£¡<br>ä¸¦å®‰è£ã€‚',
	saf_install: 'ä¸¦å®‰è£ã€‚',
	loading : 'è¼‰å…¥ä¸­â€¦',
	centeredtext : 'è¼‰å…¥ä¸­... è«‹ç¨ç­‰ã€‚',
	id_HEADER1 : 'æ‚¨çš„ç³»çµ±ä¸­æ„ŸæŸ“äº†3å€‹ç—…æ¯’',
	id_E1STPAR_HEAD : 'æ‚¨çš„PCæ„ŸæŸ“äº†',
	id_E1STPAR_VIRUS : 'ç—…æ¯’ã€‚æˆ‘å€‘çš„å®‰å…¨æª¢æŸ¥ç™¼ç¾äº†',
	id_E1STPAR_MALWARE : 'æƒ¡æ„è»Ÿé«”å’Œ&nbsp;',
	id_E1STPAR : 'é‡£é­š/é–“è«œè»Ÿé«”ã€‚ç³»çµ±ææ¯€ï¼š28.1% - éœ€è¦ç«‹å³ç§»é™¤ï¼',
	id_2NDPAR1 : 'éœ€è¦ç«‹å³ç§»é™¤ç—…æ¯’ï¼Œé¿å…ç³»çµ±é€²ä¸€æ­¥ææ¯€ï¼Œæ‡‰ç”¨ã€ç›¸ç‰‡æˆ–å…¶ä»–æª”æ¡ˆä¸Ÿå¤±ã€‚',
	id_E2NDPAR2_TRACES : 'ç™¼ç¾',
	id_E2NDPAR2 : 'æ‚¨çš„PC ä¸Šæœ‰é‡£é­š/é–“è«œè»Ÿé«”ï¼Œ',
	id_E2NDPAR3 : 'æ‚¨çš„å€‹äººè³‡æ–™å’ŒéŠ€è¡Œè³‡æ–™æœ‰å±éšªã€‚',
	id_E3RDPAR : 'ç‚ºé¿å…æ›´å¤šææ¯€ï¼Œè«‹å³åˆ»é»žé¸'+"ã€Œç«‹å³æŽƒæã€"+ 'ã€‚æˆ‘å€‘çš„æ·±åº¦æŽƒæå°‡ç«‹å³ç‚ºæ‚¨æä¾›å¹«åŠ©ï¼',
	id_E32RDPARTIMER_MINUTE: 'åˆ†',
	id_E32RDPARTIMER : 'ç§’å‰©é¤˜ï¼Œæ­¤å¾Œå°‡æ°¸ä¹…ææ¯€ã€‚',
	id_BUTTON: 'ç«‹å³æŽƒæ',
	id_SCANPROG : 'æ­£åœ¨æŽƒæ',
	id_DOWNLOADNEEDED : 'éœ€è¦ä¸‹è¼‰',
	id_HEAVILYDAMAGED : 'æ‚¨çš„PCå·²åš´é‡ææ¯€ï¼ (33.2%)',
	id_DOWNLOADMACKEEPER : 'è«‹ä¸‹è¼‰',
	id_DOWNLOADMACKEEPER_VIRUS : 'æ‡‰ç”¨ç¨‹å¼ä»¥ç§»é™¤æ‚¨PCä¸Šçš„3å€‹ç—…æ¯’ã€‚',
	id_VIRUSINFO : 'ç—…æ¯’è³‡è¨Š',
	id_VIRNAME : 'ç—…æ¯’åç¨±ï¼š&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'é¢¨éšªç­‰ç´šï¼š&nbsp;&nbsp;é«˜',
	id_INFECTEDDATA: 'æ„ŸæŸ“çš„æª”æ¡ˆï¼š&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'ç«‹å³ç§»é™¤ç—…æ¯’',
	id_VIRUSREMOVAL : 'ç—…æ¯’ç§»é™¤',
	id_APPLICATION : 'æ‡‰ç”¨ï¼š&nbsp;',
	id_RATING : 'è©•åˆ†ï¼š&nbsp;&nbsp;9.9/10',
	id_PRICE : 'åƒ¹æ ¼ï¼š&nbsp;&nbsp;å…è²»',
	alertwindow : "éœ€è¦ç«‹å³è¡Œå‹•\n\næˆ‘å€‘åœ¨æ‚¨çš„PCä¸Šåµæ¸¬åˆ°ä¸€å€‹æœ¨é¦¬ç—…æ¯’ (e.tre456_worm_Windows)ã€‚\n\né»žé¸ã€Œå¥½ã€é–‹å§‹ä¿®å¾©ç¨‹åºã€‚",
	loadingtext1 : "è¼‰å…¥ä¸­",
	loadingtext2 : "æ­£åœ¨æŽƒæ...æª”æ¡ˆ",
	loadingtext3 : "æ­£åœ¨æŽƒæ...æ–‡ä»¶",
	loadingtext4 : "æ­£åœ¨æŽƒæ...ç³»çµ±æª”",
	loadingtext5 : "æ­£åœ¨æŽƒæ...ç™»éŒ„æª”",
	loadingtext6 : "æŽƒæå®Œæˆ",
	virfoundtext1 : "ç™¼ç¾çš„ç—…æ¯’ï¼šRansomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "æ­£åœ¨æœå°‹ç§»é™¤é¸é …...",
};

/*
* Thai
*/
var thSet = {
	saf_overlay_P_5: 'à¹‚à¸›à¸£à¸”à¸„à¸¥à¸´à¸à¸ªà¸±à¸à¸¥à¸±à¸à¸©à¸“à¹Œà¸”à¸²à¸§à¸™à¹Œà¹‚à¸«à¸¥à¸”',
	overlay_P_5: 'à¸„à¸¥à¸´à¸<br>à¸—à¸µà¹ˆà¸™à¸µà¹ˆ<br>à¹à¸¥à¸°à¸•à¸´à¸”à¸•à¸±à¹‰à¸‡',
	saf_install: ' à¹à¸¥à¸°à¸•à¸´à¸”à¸•à¸±à¹‰à¸‡',
	loading : 'à¸à¸³à¸¥à¸±à¸‡à¹‚à¸«à¸¥à¸”...',
	centeredtext : 'à¸à¸³à¸¥à¸±à¸‡à¹‚à¸«à¸¥à¸”... à¹‚à¸›à¸£à¸”à¸£à¸­',
	id_HEADER1 : 'à¸£à¸°à¸šà¸šà¸‚à¸­à¸‡à¸„à¸¸à¸“à¸•à¸´à¸”à¹€à¸Šà¸·à¹‰à¸­à¹„à¸§à¸£à¸±à¸ª 3 à¸£à¸²à¸¢à¸à¸²à¸£',
	id_E1STPAR_HEAD : 'PC à¸‚à¸­à¸‡à¸„à¸¸à¸“à¸•à¸´à¸”à¹€à¸Šà¸·à¹‰à¸­',
	id_E1STPAR_VIRUS : 'à¹„à¸§à¸£à¸±à¸ª à¸à¸²à¸£à¸•à¸£à¸§à¸ˆà¸ªà¸­à¸šà¸„à¸§à¸²à¸¡à¸›à¸¥à¸­à¸”à¸ à¸±à¸¢à¸‚à¸­à¸‡à¹€à¸£à¸²à¸žà¸šà¸£à¹ˆà¸­à¸‡à¸£à¸­à¸¢à¸‚à¸­à¸‡',
	id_E1STPAR_MALWARE : 'à¸¡à¸±à¸¥à¹à¸§à¸£à¹Œà¹à¸¥à¸°',
	id_E1STPAR : 'à¸à¸²à¸£à¸Ÿà¸´à¸Šà¸Šà¸´à¹ˆà¸‡/à¸ªà¸›à¸²à¸¢à¹à¸§à¸£à¹Œ à¸„à¸§à¸²à¸¡à¹€à¸ªà¸µà¸¢à¸«à¸²à¸¢à¸‚à¸­à¸‡à¸£à¸°à¸šà¸š: 28.1% - à¸•à¹‰à¸­à¸‡à¸à¸³à¸ˆà¸±à¸”à¸—à¸±à¸™à¸—à¸µ!',
	id_2NDPAR1 : 'à¸•à¹‰à¸­à¸‡à¸à¸³à¸ˆà¸±à¸”à¹„à¸§à¸£à¸±à¸ªà¸—à¸±à¸™à¸—à¸µà¹€à¸žà¸·à¹ˆà¸­à¸›à¹‰à¸­à¸‡à¸à¸±à¸™à¸„à¸§à¸²à¸¡à¹€à¸ªà¸µà¸¢à¸«à¸²à¸¢à¸‚à¸­à¸‡à¸£à¸°à¸šà¸šà¹€à¸žà¸´à¹ˆà¸¡à¹€à¸•à¸´à¸¡ à¸à¸²à¸£à¸ªà¸¹à¸à¹€à¸ªà¸µà¸¢à¹à¸­à¸› à¸£à¸¹à¸›à¸ à¸²à¸žà¸«à¸£à¸·à¸­à¹„à¸Ÿà¸¥à¹Œà¸­à¸·à¹ˆà¸™ à¹†',
	id_E2NDPAR2_TRACES : 'à¸žà¸šà¸£à¹ˆà¸­à¸‡à¸£à¸­à¸¢à¸‚à¸­à¸‡',
	id_E2NDPAR2 : 'à¸Ÿà¸´à¸Šà¸Šà¸´à¹ˆà¸‡/à¸ªà¸›à¸²à¸¢à¹à¸§à¸£à¹Œà¸šà¸™ PC à¸‚à¸­à¸‡à¸„à¸¸à¸“à¸”à¹‰à¸§à¸¢',
	id_E2NDPAR3 : 'à¸‚à¹‰à¸­à¸¡à¸¹à¸¥à¸ªà¹ˆà¸§à¸™à¸•à¸±à¸§à¹à¸¥à¸°à¸‚à¹‰à¸­à¸¡à¸¹à¸¥à¸˜à¸™à¸²à¸„à¸²à¸£à¸à¸³à¸¥à¸±à¸‡à¸•à¸à¸­à¸¢à¸¹à¹ˆà¹ƒà¸™à¸„à¸§à¸²à¸¡à¹€à¸ªà¸µà¹ˆà¸¢à¸‡',
	id_E3RDPAR : 'à¹€à¸žà¸·à¹ˆà¸­à¹€à¸¥à¸µà¹ˆà¸¢à¸‡à¸„à¸§à¸²à¸¡à¹€à¸ªà¸µà¸¢à¸«à¸²à¸¢à¹€à¸žà¸´à¹ˆà¸¡à¹€à¸•à¸´à¸¡ à¸„à¸¥à¸´à¸ '+"'à¸ªà¹à¸à¸™à¸•à¸­à¸™à¸™à¸µà¹‰'"+ ' à¸—à¸±à¸™à¸—à¸µ à¸à¸²à¸£à¸ªà¹à¸à¸™à¹€à¸Šà¸´à¸‡à¸¥à¸¶à¸à¸‚à¸­à¸‡à¹€à¸£à¸²à¸ˆà¸°à¸¡à¸­à¸šà¸à¸²à¸£à¸Šà¹ˆà¸§à¸¢à¹€à¸«à¸¥à¸·à¸­à¹ƒà¸«à¹‰à¹ƒà¸™à¸—à¸±à¸™à¸—à¸µ!',
	id_E32RDPARTIMER_MINUTE: 'à¸™à¸²à¸—à¸µà¹à¸¥à¸° ',
	id_E32RDPARTIMER : 'à¸§à¸´à¸™à¸²à¸—à¸µà¹€à¸«à¸¥à¸·à¸­à¸­à¸¢à¸¹à¹ˆà¸à¹ˆà¸­à¸™à¸„à¸§à¸²à¸¡à¹€à¸ªà¸µà¸¢à¸«à¸²à¸¢à¸ˆà¸°à¸„à¸‡à¸­à¸¢à¸¹à¹ˆà¸–à¸²à¸§à¸£',
	id_BUTTON: 'à¸ªà¹à¸à¸™à¸•à¸­à¸™à¸™à¸µà¹‰',
	id_SCANPROG : 'à¸à¸³à¸¥à¸±à¸‡à¸­à¸¢à¸¹à¹ˆà¸£à¸°à¸«à¸§à¹ˆà¸²à¸‡à¸à¸²à¸£à¸ªà¹à¸à¸™',
	id_DOWNLOADNEEDED : 'à¸•à¹‰à¸­à¸‡à¸”à¸²à¸§à¸™à¹Œà¹‚à¸«à¸¥à¸”',
	id_HEAVILYDAMAGED : 'PC à¸‚à¸­à¸‡à¸„à¸¸à¸“à¹€à¸ªà¸µà¸¢à¸«à¸²à¸¢à¸­à¸¢à¹ˆà¸²à¸‡à¸£à¸¸à¸™à¹à¸£à¸‡! (33.2%)',
	id_DOWNLOADMACKEEPER : 'à¹‚à¸›à¸£à¸”à¸”à¸²à¸§à¸™à¹Œà¹‚à¸«à¸¥à¸”',
	id_DOWNLOADMACKEEPER_VIRUS : 'à¹à¸­à¸›à¸žà¸¥à¸´à¹€à¸„à¸Šà¸±à¸™à¹€à¸žà¸·à¹ˆà¸­à¸à¸³à¸ˆà¸±à¸”à¹„à¸§à¸£à¸±à¸ª 3 à¸£à¸²à¸¢à¸à¸²à¸£à¸­à¸­à¸à¸ˆà¸²à¸ PC à¸‚à¸­à¸‡à¸„à¸¸à¸“',
	id_VIRUSINFO : 'à¸‚à¹‰à¸­à¸¡à¸¹à¸¥à¹„à¸§à¸£à¸±à¸ª',
	id_VIRNAME : 'à¸Šà¸·à¹ˆà¸­à¹„à¸§à¸£à¸±à¸ª:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'à¸„à¸§à¸²à¸¡à¹€à¸ªà¸µà¹ˆà¸¢à¸‡:&nbsp;&nbsp;à¸ªà¸¹à¸‡',
	id_INFECTEDDATA: 'à¹„à¸Ÿà¸¥à¹Œà¸—à¸µà¹ˆà¸•à¸´à¸”à¹€à¸Šà¸·à¹‰à¸­:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'à¸à¸³à¸ˆà¸±à¸”à¹„à¸§à¸£à¸±à¸ªà¸•à¸­à¸™à¸™à¸µà¹‰',
	id_VIRUSREMOVAL : 'à¸à¸²à¸£à¸à¸³à¸ˆà¸±à¸”à¹„à¸§à¸£à¸±à¸ª',
	id_APPLICATION : 'à¹à¸­à¸›à¸žà¸¥à¸´à¹€à¸„à¸Šà¸±à¸™:&nbsp;',
	id_RATING : 'à¸„à¸°à¹à¸™à¸™:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'à¸£à¸²à¸„à¸²:&nbsp;&nbsp;à¸Ÿà¸£à¸µ',
	alertwindow : "à¸•à¹‰à¸­à¸‡à¸à¸²à¸£à¸à¸²à¸£à¸”à¸³à¹€à¸™à¸´à¸™à¸à¸²à¸£à¸—à¸±à¸™à¸—à¸µ\n\nà¹€à¸£à¸²à¸•à¸£à¸§à¸ˆà¸žà¸šà¹„à¸§à¸£à¸±à¸ªà¹‚à¸—à¸£à¸ˆà¸±à¸™ (e.tre456_worm_Windows) à¸šà¸™ PC à¸‚à¸­à¸‡à¸„à¸¸à¸“\n\nà¸à¸” à¸•à¸à¸¥à¸‡ à¹€à¸žà¸·à¹ˆà¸­à¹€à¸£à¸´à¹ˆà¸¡à¸à¸£à¸°à¸šà¸§à¸™à¸à¸²à¸£à¸‹à¹ˆà¸­à¸¡à¹à¸‹à¸¡",
	loadingtext1 : "à¸à¸³à¸¥à¸±à¸‡à¹‚à¸«à¸¥à¸”",
	loadingtext2 : "à¸à¸³à¸¥à¸±à¸‡à¸ªà¹à¸à¸™... à¹‚à¸Ÿà¸¥à¹€à¸”à¸­à¸£à¹Œ",
	loadingtext3 : "à¸à¸³à¸¥à¸±à¸‡à¸ªà¹à¸à¸™... à¹€à¸­à¸à¸ªà¸²à¸£",
	loadingtext4 : "à¸à¸³à¸¥à¸±à¸‡à¸ªà¹à¸à¸™... à¹„à¸Ÿà¸¥à¹Œà¸£à¸°à¸šà¸š",
	loadingtext5 : "à¸à¸³à¸¥à¸±à¸‡à¸ªà¹à¸à¸™... à¸£à¸µà¸ˆà¸´à¸ªà¸—à¸£à¸µ",
	loadingtext6 : "à¸à¸²à¸£à¸ªà¹à¸à¸™à¹€à¸ªà¸£à¹‡à¸ˆà¸ªà¸´à¹‰à¸™",
	virfoundtext1 : "à¹„à¸§à¸£à¸±à¸ªà¸—à¸µà¹ˆà¸žà¸š: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "à¸à¸³à¸¥à¸±à¸‡à¸„à¹‰à¸™à¸«à¸²à¸•à¸±à¸§à¹€à¸¥à¸·à¸­à¸à¹ƒà¸™à¸à¸²à¸£à¸à¸³à¸ˆà¸±à¸”...",
};

/*
* Turkish
*/
var trSet = {
	saf_overlay_P_5: 'LÃ¼tfen indir sembolÃ¼ne tÄ±kla',
	overlay_P_5: '<br> Buraya <br> tÄ±kla ve yÃ¼kle.',
	saf_install: ' ve yÃ¼kle.',
	loading : 'YÃ¼kleniyorâ€¦',
	centeredtext : 'YÃœKLENÄ°YOR... LÃœTFEN BEKLE.',
	id_HEADER1 : 'Sistemine 3 virÃ¼s bulaÅŸmÄ±ÅŸ',
	id_E1STPAR_HEAD : 'PC\'ine',
	id_E1STPAR_VIRUS : 'virÃ¼s bulaÅŸmÄ±ÅŸ. GÃ¼venlik kontrolÃ¼mÃ¼zde ÅŸu izler bulundu:',
	id_E1STPAR_MALWARE : 'kÃ¶tÃ¼ amaÃ§lÄ± yazÄ±lÄ±m ve&nbsp;',
	id_E1STPAR : 'kimlik hÄ±rsÄ±zlÄ±ÄŸÄ±/casus yazÄ±lÄ±m. Sistem hasarÄ±: %28,1 - Hemen kaldÄ±rÄ±lmasÄ± gereklidir!',
	id_2NDPAR1 : 'Daha fazla sistem hasarÄ±nÄ±n, UygulamalarÄ±n, FotoÄŸraflarÄ±n ve diÄŸer dosyalarÄ±n kaybolmasÄ±nÄ± Ã¶nlemek iÃ§in virÃ¼slerin hemen kaldÄ±rÄ±lmasÄ± gereklidir.',
	id_E2NDPAR2_TRACES : 'PC\'inde',
	id_E2NDPAR2 : 'kimlik hÄ±rsÄ±zlÄ±ÄŸÄ±/casus yazÄ±lÄ±m bulundu ve',
	id_E2NDPAR3 : 'KiÅŸisel bilgiler ve bankacÄ±lÄ±k bilgileri tehlikede.',
	id_E3RDPAR : 'Daha fazla hasarÄ± Ã¶nlemek iÃ§in hemen '+"'Åžimdi Tara'"+ 'dÃ¼ÄŸmesine tÄ±kla. Derin taramamÄ±z hemen yardÄ±m sunacaktÄ±r!',
	id_E32RDPARTIMER_MINUTE: 'dakika ve ',
	id_E32RDPARTIMER : 'saniye iÃ§inde hasar kalÄ±cÄ± olacaktÄ±r.',
	id_BUTTON: 'Åžimdi Tara',
	id_SCANPROG : 'TARAMA SÃœRÃœYOR',
	id_DOWNLOADNEEDED : 'Ä°NDÄ°RME GEREKLÄ°DÄ°R',
	id_HEAVILYDAMAGED : 'PC\'in aÄŸÄ±r hasar gÃ¶rmÃ¼ÅŸ! (%33,2)',
	id_DOWNLOADMACKEEPER : 'LÃ¼tfen',
	id_DOWNLOADMACKEEPER_VIRUS : 'uygulamayÄ± indirerek PC\'inden 3 VirÃ¼sÃ¼ kaldÄ±r.',
	id_VIRUSINFO : 'VIRÃœS BÄ°LGÄ°LERÄ°',
	id_VIRNAME : 'Virus Name:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risk:&nbsp;&nbsp;YÃœKSEK',
	id_INFECTEDDATA: 'BULAÅžMIÅž Files:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'VÄ°RÃœSLERÄ° ÅžÄ°MDÄ° KALDIR',
	id_VIRUSREMOVAL : 'VIRÃœS KALDIRMA Ä°ÅžLEMÄ°',
	id_APPLICATION : 'Uygulama:&nbsp;',
	id_RATING : 'Puan:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'Fiyat:&nbsp;&nbsp;Free',
	alertwindow : "HEMEN EYLEM GEREKLÄ°DÄ°R\n\nPC'inde bir truva atÄ± (e.tre456_worm_Windows) tespit ettik.\n\nOnarÄ±m sÃ¼recini baÅŸlatmak iÃ§in Tamam dÃ¼ÄŸmesine bas.",
	loadingtext1 : "YÃ¼kleniyor",
	loadingtext2 : "TaranÄ±yor... KlasÃ¶rler",
	loadingtext3 : "TaranÄ±yor... Belgeler",
	loadingtext4 : "TaranÄ±yor... Sistem DosyalarÄ±",
	loadingtext5 : "TaranÄ±yor... KayÄ±t Defteri",
	loadingtext6 : "Tarama TamamlandÄ±",
	virfoundtext1 : "VirÃ¼s Bulundu: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "KaldÄ±rma seÃ§enekleri aranÄ±yor...",
};

/*
* Korean
*/
var koSet = {
	saf_overlay_P_5: 'ë‹¤ìš´ë¡œë“œ ì‹¬ë³¼ì„ í´ë¦­í•˜ì‹­ì‹œì˜¤',
	overlay_P_5: '<br> ì—¬ê¸° <br>ë¥¼ í´ë¦­í•˜ì—¬ ì„¤ì¹˜í•˜ì‹­ì‹œì˜¤.',
	saf_install: ' ê·¸ë¦¬ê³  ì„¤ì¹˜í•˜ì‹­ì‹œì˜¤.',
	loading : 'ë¡œë”© ì¤‘â€¦',
	centeredtext : 'ë¡œë”© ì¤‘... ìž ì‹œ ê¸°ë‹¤ë ¤ ì£¼ì„¸ìš”.',
	id_HEADER1 : 'ì‹œìŠ¤í…œì´ 3ì¢…ì˜ ë°”ì´ëŸ¬ìŠ¤ì— ê°ì—¼ë˜ì—ˆìŠµë‹ˆë‹¤',
	id_E1STPAR_HEAD : 'ë‹¹ì‹ ì˜ PCì´ ë°”ì´ëŸ¬ìŠ¤ì—',
	id_E1STPAR_VIRUS : 'ê°ì—¼ë˜ì—ˆìŠµë‹ˆë‹¤. ì €í¬ ì‹œíë¦¬í‹°ì²´í¬ëŠ” ',
	id_E1STPAR_MALWARE : 'ì•…ì„±ì½”ë“œì™€&nbsp;',
	id_E1STPAR : 'í”¼ì‹±/ìŠ¤íŒŒì´ì›¨ì–´ë¥¼ ë°œê²¬í–ˆìŠµë‹ˆë‹¤. ì‹œìŠ¤í…œì†ìƒ: 28.1% - ì¦‰ì‹œ ì œê±°í•´ì•¼ í•©ë‹ˆë‹¤!',
	id_2NDPAR1 : 'ë°”ì´ëŸ¬ìŠ¤ë¥¼ ì¦‰ì‹œ ì œê±°í•´ì•¼ ì‹œìŠ¤í…œ ì†ìƒê³¼ ì•±, ì‚¬ì§„ì„ ë¹„ë¡¯í•œ ê¸°íƒ€ íŒŒì¼ì˜ ë” í° ì†ìƒì„ ë§‰ì„ ìˆ˜ ìžˆìŠµë‹ˆë‹¤.',
	id_E2NDPAR2_TRACES : 'ë°”ì´ëŸ¬ìŠ¤ì˜ í”ì :',
	id_E2NDPAR2 : 'í”¼ì‹±/ìŠ¤íŒŒì´ì›¨ì–´ê°€ ë‹¹ì‹ ì˜ PCì—ì„œ ë°œê²¬ë˜ì—ˆìœ¼ë©°,',
	id_E2NDPAR3 : 'ê°œì¸ ì •ë³´ì™€ ì€í–‰ ì •ë³´ê°€ ìœ„í—˜í•©ë‹ˆë‹¤.',
	id_E3RDPAR : 'ë” í° í”¼í•´ë¥¼ ë§‰ìœ¼ë ¤ë©´, ì¦‰ì‹œ '+"'ì§€ê¸ˆ ìŠ¤ìº”í•˜ê¸°'"+'ë¥¼ í´ë¦­í•˜ì‹­ì‹œì˜¤. ì €í¬ ë”¥ ìŠ¤ìº”ì´ ì¦‰ì‹œ ë„ì™€ë“œë¦¬ê² ìŠµë‹ˆë‹¤!',
	id_E32RDPARTIMER_MINUTE: 'ë¶„ ',
	id_E32RDPARTIMER : 'ì´ˆ í›„ì—ëŠ” í”¼í•´ê°€ ì˜êµ¬í™”ë©ë‹ˆë‹¤.',
	id_BUTTON: 'ì§€ê¸ˆ ìŠ¤ìº”',
	id_SCANPROG : 'ìŠ¤ìº” ì¤‘',
	id_DOWNLOADNEEDED : 'í•„ìˆ˜ ìš”ì†Œ ë‹¤ìš´ë¡œë“œ',
	id_HEAVILYDAMAGED : 'ë‹¹ì‹ ì˜ PCì´ ì‹¬ê°í•˜ê²Œ ì†ìƒë˜ì—ˆìŠµë‹ˆë‹¤! (33.2%)',
	id_DOWNLOADMACKEEPER : 'ë‹¤ìŒ ì•±ì„ ë‹¤ìš´ë¡œë“œí•˜ì‹­ì‹œì˜¤:',
	id_DOWNLOADMACKEEPER_VIRUS : 'PCì—ì„œ 3 ì¢…ì˜ ë°”ì´ëŸ¬ìŠ¤ë¥¼ ì œê±°í•˜ëŠ” ì• í”Œë¦¬ì¼€ì´ì…˜.',
	id_VIRUSINFO : 'ë°”ì´ëŸ¬ìŠ¤ ì •ë³´',
	id_VIRNAME : 'ë°”ì´ëŸ¬ìŠ¤ ì´ë¦„:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'ìœ„í—˜ë„:&nbsp;&nbsp;ë†’ìŒ',
	id_INFECTEDDATA: 'ê°ì—¼ëœ íŒŒì¼:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'ì§€ê¸ˆ ë°”ì´ëŸ¬ìŠ¤ ì œê±°',
	id_VIRUSREMOVAL : 'ë°”ì´ëŸ¬ìŠ¤ ì œê±°',
	id_APPLICATION : 'ì• í”Œë¦¬ì¼€ì´ì…˜:&nbsp;',
	id_RATING : 'í‰ê°€:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'ê°€ê²©:&nbsp;&nbsp;ë¬´ë£Œ',
	alertwindow : "ì¦‰ê°ì ì¸ í–‰ë™ í•„ìš”í•©ë‹ˆë‹¤\n\në‹¹ì‹ ì˜ PCì—ì„œ íŠ¸ë¡œì´ ëª©ë§ˆ ë°”ì´ëŸ¬ìŠ¤(e.tre456_worm_Windows)ë¥¼ íƒì§€í–ˆìŠµë‹ˆë‹¤.\n\në¦¬íŽ˜ì–´ ê³¼ì •ì„ ì‹œìž‘í•˜ë ¤ë©´ OKë¥¼ ëˆ„ë¥´ì‹­ì‹œì˜¤.",
	loadingtext1 : "ë¡œë”© ì¤‘",
	loadingtext2 : "í´ë”... ìŠ¤ìº” ì¤‘",
	loadingtext3 : "ë¬¸ì„œ... ìŠ¤ìº” ì¤‘",
	loadingtext4 : "ì‹œìŠ¤í…œ íŒŒì¼... ìŠ¤ìº” ì¤‘",
	loadingtext5 : "ë ˆì§€ìŠ¤íŠ¸ë¦¬... ìŠ¤ìº” ì¤‘",
	loadingtext6 : "ìŠ¤ìº” ì™„ë£Œ",
	virfoundtext1 : "ë°”ì´ëŸ¬ìŠ¤ ë°œê²¬: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "ë°”ì´ëŸ¬ìŠ¤ ì œê±° ì˜µì…˜ íƒìƒ‰ ì¤‘...",
};

/*
* Dutch
*/
var nlSet = {
	saf_overlay_P_5: 'Klik op het downloadsymbool',
	overlay_P_5: 'Click <br> hier <br> en installeer.',
	saf_install: ' en installeer.',
	loading : 'Aan het ladenâ€¦',
	centeredtext : 'AAN HET LADEN... EVEN GEDULD.',
	id_HEADER1 : 'Uw systeem is besmet met 3 virussen',
	id_E1STPAR_HEAD : 'Uw PC is besmet met',
	id_E1STPAR_VIRUS : 'virussen. Onze veiligheidscontrole heeft sporen gevonden van',
	id_E1STPAR_MALWARE : 'malware en&nbsp;',
	id_E1STPAR : 'phishing/spyware. Systeemschade: 28,1% - Onmiddellijke verwijdering vereist!',
	id_2NDPAR1 : 'De onmiddellijke verwijdering van de virussen is vereist om verdere systeemschade en het verlies van apps, fotoâ€™s en andere bestanden te voorkomen.',
	id_E2NDPAR2_TRACES : 'Sporen van',
	id_E2NDPAR2 : 'phishing/spyware zijn op uw PC aangetroffen met',
	id_E2NDPAR3 : 'Uw persoonlijke en bankinformatie zijn in gevaar.',
	id_E3RDPAR : 'Om verdere schade te voorkomen, klik onmiddelijk op '+"'Nu scannen'"+'Onze diepe scan zal onmiddellijk hulp bieden!',
	id_E32RDPARTIMER_MINUTE: 'minuut en ',
	id_E32RDPARTIMER : 'seconden voordat de schade permanent wordt.',
	id_BUTTON: 'Nu scannen',
	id_SCANPROG : 'AAN HET SCANNEN',
	id_DOWNLOADNEEDED : 'DOWNLOAD VEREIST',
	id_HEAVILYDAMAGED : 'Uw PC heeft aanzienlijke schade! (33,2%)',
	id_DOWNLOADMACKEEPER : 'Download de',
	id_DOWNLOADMACKEEPER_VIRUS : 'applicatie om 3 virussen van uw PC te verwijderen.',
	id_VIRUSINFO : 'VIRUSINFORMATIE',
	id_VIRNAME : 'Virusnaam:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risico:&nbsp;&nbsp;HOOG',
	id_INFECTEDDATA: 'Besmette bestanden:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'VIRUSSEN NU VERWIJDEREN',
	id_VIRUSREMOVAL : 'VIRUSVERWIJDERING',
	id_APPLICATION : 'Applicatie:&nbsp;',
	id_RATING : 'Beoordeling:&nbsp;&nbsp;9,9/10',
	id_PRICE : 'Prijs:&nbsp;&nbsp;Gratis',
	alertwindow : "ONMIDDELLIJKE ACTIE VEREIST \n\nWe hebben een Trojaans virus (e.tre456_worm_Windows) op uw PC gedetecteerd.\n\nDruk op OK om het reparatieproces te starten.",
	loadingtext1 : "Aan het laden",
	loadingtext2 : "Scannen... Mappen",
	loadingtext3 : "Scannen... Documenten",
	loadingtext4 : "Scannen... Systeembestanden ",
	loadingtext5 : "Scannen... Register",
	loadingtext6 : "Scan compleet",
	virfoundtext1 : "Gevonden virus: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Aan het zoeken naar verwijderingsopties...",
	alert2text : "Een moment alstublieft!\n\nWindows hebben gedetecteerd, dat u uw Windows-systeem niet hebt bijgewerkt.\n\nWerk uw systeem bij, voordat uw bestanden worden verwijderd.\n\nVerlaat deze pagina niet voordat, u uw systeemsoftware heeft bijgewerkt.\n\nBedankt."
};

/*
* Danish
*/
var daSet = {
	saf_overlay_P_5: 'Klik venligst pÃ¥ download-symbolet',
	overlay_P_5: 'Klik <br> her <br> og installer.',
	saf_install: ' og installer.',
	loading : 'IndlÃ¦serâ€¦',
	centeredtext : 'INDLÃ†SER... VENT VENLIGST.',
	id_HEADER1 : 'Dit system er inficeret med 3 virusser',
	id_E1STPAR_HEAD : 'Din PC er inficeret med',
	id_E1STPAR_VIRUS : 'virusser. Vores sikkerhedstjek har fundet spor af',
	id_E1STPAR_MALWARE : 'malware og&nbsp;',
	id_E1STPAR : 'phishing/spyware. Systemskade: 28.1% - OmgÃ¥ende fjernelse pÃ¥krÃ¦vet!',
	id_2NDPAR1 : 'Den omgÃ¥ende fjernelse af virusserne er nÃ¸dvendig for at forebygge yderligere skade pÃ¥ systemet og tab af apper, fotos eller andre filer.',
	id_E2NDPAR2_TRACES : 'Spor af',
	id_E2NDPAR2 : 'phishing/spyware blev fundet pÃ¥ din PC med',
	id_E2NDPAR3 : 'Private og bankoplysninger er i fare.',
	id_E3RDPAR : 'For at undgÃ¥ flere skader, klik pÃ¥ '+"'Scan nu'"+ 'straks. Vores grundige scanning hjÃ¦lper straks!',
	id_E32RDPARTIMER_MINUTE: 'minut og ',
	id_E32RDPARTIMER : 'sekunder tilbage fÃ¸r skaden er permanent.',
	id_BUTTON: 'Scan nu',
	id_SCANPROG : 'SCANNING I GANG',
	id_DOWNLOADNEEDED : 'DOWNLOAD NÃ˜DVENDIGT',
	id_HEAVILYDAMAGED : 'Din PC er alvorligt skadet! (33.2%)',
	id_DOWNLOADMACKEEPER : 'Download venligst',
	id_DOWNLOADMACKEEPER_VIRUS : 'applikationen for at fjerne 3 virusser fra din PC.',
	id_VIRUSINFO : 'VIRUS-INFORMATION',
	id_VIRNAME : 'Virus-navn:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risk:&nbsp;&nbsp;HÃ˜J',
	id_INFECTEDDATA: 'Inficerede filer:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'FJERN VIRUSSER NU',
	id_VIRUSREMOVAL : 'FJERNELSE AF VIRUSSER',
	id_APPLICATION : 'Applikation:&nbsp;',
	id_RATING : 'BedÃ¸mmelse:&nbsp;&nbsp;9.9/10',
	id_PRICE : 'Pris:&nbsp;&nbsp;Gratis',
	alertwindow : "OMGÃ…ENDE HANDLING NÃ˜DVENDIGVi har opdaget en trojanervirus (e.tre456_worm_Windows) pÃ¥ din PC. Tryk OK for at begynde reparationsprocessen.",
	loadingtext1 : "IndlÃ¦ser",
	loadingtext2 : "Scanner... Mapper",
	loadingtext3 : "Scanner... Dokumenter",
	loadingtext4 : "Scanner... Systemfiler",
	loadingtext5 : "Scanner... Registeret",
	loadingtext6 : "Scan FÃ¦rdigt",
	virfoundtext1 : "Virus fundet: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "Leder efter muligheder for fjernelse...",
	alert2text: "Microsoft har registreret, at dit Microsoft Windows-system i Ã¸jeblikket ikke er opdateret og beskadiget.\n\nDette medfÃ¸rer, at dine systemfiler automatisk bliver slettet.\n\nFÃ¸lg vejledningen med det samme for at lÃ¸se problemet og sikre, at dit system forbliver opdateret."
};

/*PC
* Finnish
*/
var fiSet = {
	saf_overlay_P_5: 'Napsauta latauskuvaketta',
	overlay_P_5: 'Napsauta <br> tÃ¤stÃ¤ <br> asentaaksesi.',
	saf_install: ' asentaaksesi.',
	loading : 'Ladataanâ€¦',
	centeredtext : 'LADATAAN... ODOTA HETKI.',
	id_HEADER1 : 'JÃ¤rjestelmÃ¤stÃ¤si lÃ¶ytyi 3 virustartuntaa',
	id_E1STPAR_HEAD : 'PCiltasi lÃ¶ytyi',
	id_E1STPAR_VIRUS : 'virusta. Turvatarkastuksemme lÃ¶ysi jÃ¤lkiÃ¤',
	id_E1STPAR_MALWARE : 'haittaohjelmasta ja&nbsp;',
	id_E1STPAR : 'tietojenkalastelusta/vakoiluohjelmasta. JÃ¤rjestelmÃ¤n vauriotila: 28,1 % - Suorita korjaustoimenpiteet vÃ¤littÃ¶mÃ¤sti!',
	id_2NDPAR1 : 'Sinun tulee poistaa virukset vÃ¤littÃ¶mÃ¤sti estÃ¤Ã¤ksesi lisÃ¤vaurioiden aiheutumisen jÃ¤rjestelmÃ¤lle, sekÃ¤ sovellusten, valokuvien ja muiden tiedostojen menettÃ¤misen.',
	id_E2NDPAR2_TRACES : 'JÃ¤lkiÃ¤',
	id_E2NDPAR2 : 'tietojenkalastelusta/vakoiluohjelmasta, joiden johdosta',
	id_E2NDPAR3 : 'HenkilÃ¶- ja pankkitietosi ovat vaarassa.',
	id_E3RDPAR : 'EstÃ¤ lisÃ¤vahingot napsauttamalla '+"'Skannaa nyt'"+ 'vÃ¤littÃ¶mÃ¤sti. SyvÃ¤skannauksemme avustaa sinua vÃ¤littÃ¶mÃ¤sti!',
	id_E32RDPARTIMER_MINUTE: 'minuuttia ja ',
	id_E32RDPARTIMER : 'sekuntia jÃ¤ljellÃ¤ ennen kuin vahingot jÃ¤Ã¤vÃ¤t pysyviksi.',
	id_BUTTON: 'Skannaa nyt',
	id_SCANPROG : 'SKANNAUS KÃ„YNNISSÃ„',
	id_DOWNLOADNEEDED : 'LATAUS VAADITAAN',
	id_HEAVILYDAMAGED : 'PCisi on merkittÃ¤vÃ¤sti vaurioitunut! (33,2 %)',
	id_DOWNLOADMACKEEPER : 'Lataa',
	id_DOWNLOADMACKEEPER_VIRUS : '-sovellus poistaaksesi 3 virusta PCiltasi.',
	id_VIRUSINFO : 'VIRUKSEN TIEDOT',
	id_VIRNAME : 'Viruksen nimi:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Riski:&nbsp;&nbsp;HIGH',
	id_INFECTEDDATA: 'Saastuneet tiedostot:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'POISTA VIRUKSET NYT',
	id_VIRUSREMOVAL : 'VIRUSTEN POISTO',
	id_APPLICATION : 'Sovellus:&nbsp;',
	id_RATING : 'Arviot:&nbsp;&nbsp;9,9/10',
	id_PRICE : 'Hinta:&nbsp;&nbsp;Ilmainen',
	alertwindow : "VÃ„LITTÃ–MIÃ„ TOIMENPITEITÃ„ EDELLYTETÃ„Ã„N PCillasi on havaittu e.tre456_worm_Windows -virus. Paina OK aloittaaksesi korjausprosessi.",
	loadingtext1 : "Ladataan",
	loadingtext2 : "Skannataan... Kansioita",
	loadingtext3 : "Skannataan... Dokumentteja",
	loadingtext4 : "Skannataan... JÃ¤rjestelmÃ¤tiedostoja",
	loadingtext5 : "Skannataan... RekisteriÃ¤",
	loadingtext6 : "Skannaus valmis",
	virfoundtext1 : "LÃ¶ydetty virus: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "EtsitÃ¤Ã¤n tietoa poistotavoista...",
	alert2text: "Microsoft on havainnut ettÃ¤ et ole pÃ¤ivittÃ¤nyt Windows-jÃ¤rjestelmÃ¤Ã¤si.\n\nSinun tulee suorittaa pÃ¤ivitys tai tiedostosi poistuvat.\n\nÃ„lÃ¤ poistu tÃ¤ltÃ¤ sivulta ennen jÃ¤rjestelmÃ¤sovelluksen pÃ¤ivittÃ¤mistÃ¤.\n\nKiitos."
};

/*
* Norwegian
*/
var noSet = {
	saf_overlay_P_5: 'Trykk pÃ¥ nedlastingssymbolet',
	overlay_P_5: 'Trykk <br> her <br> for Ã¥ installere.',
	saf_install: ' og installer.',
	loading : 'Laster â€¦',
	centeredtext : 'LASTER â€¦ VENT.',
	id_HEADER1 : 'Systemet ditt er infisert med 3 virus',
	id_E1STPAR_HEAD : 'Din PC er infisert med',
	id_E1STPAR_VIRUS : 'virus. Sikkerhetssjekken vÃ¥r fant spor av',
	id_E1STPAR_MALWARE : 'skadelig programvare og&nbsp;',
	id_E1STPAR : 'nettfisking/spionprogramvare. Systemskade: 28,1 %. Dette mÃ¥ fjernes umiddelbart!',
	id_2NDPAR1 : 'Virusene mÃ¥ fjernes umiddelbart for Ã¥ hindre mer skade pÃ¥ systemet, samt tap av programmer, bilder eller andre filer.',
	id_E2NDPAR2_TRACES : 'Spor av',
	id_E2NDPAR2 : 'nettfisking/spionprogramvare ble funnet pÃ¥ din PC',
	id_E2NDPAR3 : 'noe som betyr at personlige opplysninger og bankinfo er i faresonen.',
	id_E3RDPAR : 'Trykk pÃ¥ '+'Â«Skann nÃ¥Â»'+ 'med en gang for Ã¥ unngÃ¥ mer skade. Den grundige skanningsprosessen vÃ¥r hjelper deg umiddelbart!',
	id_E32RDPARTIMER_MINUTE: 'minutt og ',
	id_E32RDPARTIMER : 'sekunder gjenstÃ¥r fÃ¸r skaden er uopprettelig.',
	id_BUTTON: 'Skann nÃ¥',
	id_SCANPROG : 'SKANNINGEN PÃ…GÃ…R',
	id_DOWNLOADNEEDED : 'MÃ… LASTES NED',
	id_HEAVILYDAMAGED : 'Din PC er alvorlig skadet! (33,2%)',
	id_DOWNLOADMACKEEPER : 'Last ned',
	id_DOWNLOADMACKEEPER_VIRUS : 'programmet for Ã¥ fjerne 3 virus fra din PC.',
	id_VIRUSINFO : 'VIRUSINFO',
	id_VIRNAME : 'Virusnavn:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risiko:&nbsp;&nbsp;HÃ˜Y',
	id_INFECTEDDATA: 'Infiserte filer:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'FJERN VIRUS NÃ…',
	id_VIRUSREMOVAL : 'VIRUSFJERNING',
	id_APPLICATION : 'Program:&nbsp;',
	id_RATING : 'Rangering:&nbsp;&nbsp;9,9/10',
	id_PRICE : 'Pris:&nbsp;&nbsp;Free',
	alertwindow : "DU MÃ… GJÃ˜RE NOE UMIDDELBART Vi har funnet et trojansk virus (e.tre456_worm_Windows) pÃ¥ din PC.Trykk pÃ¥ Â«OKÂ» for Ã¥ starte repareringen.",
	loadingtext1 : "Laster",
	loadingtext2 : "Skanner â€¦ Mapper",
	loadingtext3 : "Skanner â€¦ Dokumenter",
	loadingtext4 : "Skanner â€¦ systemfiler",
	loadingtext5 : "Skanner â€¦ registre",
	loadingtext6 : "Skanningen er fullfÃ¸rt",
	virfoundtext1 : "Vi fant fÃ¸lgende virus: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "SÃ¸ker etter alternativer for fjerning",
	alert2text : "VÄƒ rugÄƒm sÄƒ aÈ™teptaÈ›i!\n\nMicrosoft au detectat cÄƒ nu v-aÈ›i actualizat sistemul Windows.\n\nVÄƒ rugÄƒm sÄƒ faceÈ›i acest lucru Ã®nainte ca fiÈ™ierele dvs. sÄƒ fie È™terse.\n\nNu pÄƒrÄƒsiÈ›i aceastÄƒ paginÄƒ fÄƒrÄƒ a vÄƒ actualiza software-ul sistemului.\n\nVÄƒ mulÈ›umim"
};

/*
* Swedish
*/
var svSet = {
	saf_overlay_P_5: 'VÃ¤nligen klicka pÃ¥ nedladdningssymbolen',
	overlay_P_5: 'Klicka <br> hÃ¤r <br> och installera.',
	saf_install: ' och installera.',
	loading : 'Laddarâ€¦',
	centeredtext : 'LADDAR... VÃ„NLIGEN VÃ„NTA.',
	id_HEADER1 : 'Ditt system Ã¤r infekterat med 3 virus',
	id_E1STPAR_HEAD : 'DIn PC Ã¤r infekterat med',
	id_E1STPAR_VIRUS : 'virus. VÃ¥r sÃ¤kerhetskontroll fann spÃ¥r av',
	id_E1STPAR_MALWARE : 'skadlig kod och&nbsp;',
	id_E1STPAR : 'nÃ¤tfiske/spionprogram. Systemskada: 28,1 % - omedelbart avlÃ¤gsnande krÃ¤vs!',
	id_2NDPAR1 : 'Omedelbart avlÃ¤gsnande av virus krÃ¤vs fÃ¶r att fÃ¶rhindra ytterligare systemskada, fÃ¶rlust av appar, foton eller andra filer.',
	id_E2NDPAR2_TRACES : 'SpÃ¥r av',
	id_E2NDPAR2 : 'nÃ¤tfiske/spionprogram hittades pÃ¥ din PC med',
	id_E2NDPAR3 : 'Person- och bankuppgifter Ã¤r utsatta.',
	id_E3RDPAR : 'FÃ¶r att undvika mer skada, klicka pÃ¥ '+"'Skanna nu'"+ 'omedelbart. VÃ¥r djup-skanning hjÃ¤lper dig omedelbart!',
	id_E32RDPARTIMER_MINUTE: 'minut och ',
	id_E32RDPARTIMER : 'sekunder kvarstÃ¥r innan skadan Ã¤r permanent.',
	id_BUTTON: 'Skanna nu',
	id_SCANPROG : 'SKANNING PÃ…GÃ…R',
	id_DOWNLOADNEEDED : 'NEDLADDNING KRÃ„VS',
	id_HEAVILYDAMAGED : 'Din PC Ã¤r mycket skadad! (33,2 %)',
	id_DOWNLOADMACKEEPER : 'VÃ¤nligen ladda ned',
	id_DOWNLOADMACKEEPER_VIRUS : 'applikationen fÃ¶r att avlÃ¤gsna 3 virus frÃ¥n din PC.',
	id_VIRUSINFO : 'VIRUSINFORMATION',
	id_VIRNAME : 'Virusnamn:&nbsp;&nbsp;Ransomware 2.0; Trojan.Win32.SendIP.15',
	id_VIRRISK: 'Risk:&nbsp;&nbsp;HÃ–G',
	id_INFECTEDDATA: 'Infekterade filer:&nbsp;&nbsp;C:/WINDOWS/System32/migration/ADJF9009de.@*fg/windows.exe; C:/WINDOWS/System32/Drivers/spoclsv.exe...',
	id_REMOVENOW : 'AVLÃ„GSNA VIRUS NU',
	id_VIRUSREMOVAL : 'VIRUSAVLÃ„GSNANDE',
	id_APPLICATION : 'Applikation:&nbsp;',
	id_RATING : 'Betyg:&nbsp;&nbsp;9,9/10',
	id_PRICE : 'Pris:&nbsp;&nbsp;gratis',
	alertwindow : "OMEDELBAR Ã…TGÃ„RD KRÃ„VSVi har upptÃ¤ckt ett trojanskt virus (e.tre456_worm_Windows) pÃ¥ din PC.Tryck OK fÃ¶r att pÃ¥bÃ¶rja reparationsprocessen.",
	loadingtext1 : "Laddar",
	loadingtext2 : "Skannar... mappar",
	loadingtext3 : "Skannar... dokument",
	loadingtext4 : "Skannar... systemfiler",
	loadingtext5 : "Skannar... register",
	loadingtext6 : "Skanning slutfÃ¶rd",
	virfoundtext1 : "Virus funna: Ransomware 2.0; Trojan.Win32.SendIP.15",
	virfoundtext2 : "SÃ¶ker efter avlÃ¤gsnandealternativ...",
	alert2text : "VÄƒ rugÄƒm sÄƒ aÈ™teptaÈ›i!\n\nMicrosoft au detectat cÄƒ nu v-aÈ›i actualizat sistemul Windows.\n\nVÄƒ rugÄƒm sÄƒ faceÈ›i acest lucru Ã®nainte ca fiÈ™ierele dvs. sÄƒ fie È™terse.\n\nNu pÄƒrÄƒsiÈ›i aceastÄƒ paginÄƒ fÄƒrÄƒ a vÄƒ actualiza software-ul sistemului.\n\nVÄƒ mulÈ›umim"
};